# Generated by Django 5.2.11 on 2026-02-27 18:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('pan', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('REVIEW', 'Review'), ('UNDERWRITING', 'Underwriting'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('BLACKLISTED', 'Blacklisted')], default='REVIEW', max_length=20)),
                ('eligibility_done', models.BooleanField(default=False)),
                ('kyc_done', models.BooleanField(default=False)),
                ('fraud_check_done', models.BooleanField(default=False)),
                ('aml_done', models.BooleanField(default=False)),
                ('underwriting_done', models.BooleanField(default=False)),
                ('document_execution_done', models.BooleanField(default=False)),
                ('disbursement_done', models.BooleanField(default=False)),
                ('fraud_score', models.IntegerField(default=0)),
                ('synthetic_status', models.CharField(default='CLEAR', max_length=20)),
                ('aml_status', models.CharField(default='CLEAR', max_length=20)),
                ('behavioral_risk', models.CharField(default='LOW', max_length=20)),
                ('pattern_match', models.CharField(default='NO MATCH', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pan_match', models.BooleanField(default=False)),
                ('aadhaar_match', models.BooleanField(default=False)),
                ('face_match_score', models.IntegerField(default=0)),
                ('liveness_passed', models.BooleanField(default=False)),
                ('negative_area', models.BooleanField(default=False)),
                ('income_confidence_score', models.IntegerField(default=0)),
                ('cibil_score', models.IntegerField(default=0)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('hash_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_id', models.CharField(max_length=30, unique=True)),
                ('applicant_name', models.CharField(max_length=100)),
                ('fraud_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('HIGH', 'High Risk'), ('MEDIUM', 'Medium Risk'), ('LOW', 'Low Risk')], default='LOW', max_length=10)),
                ('aml_status', models.CharField(choices=[('CLEAR', 'Clear'), ('SANCTION_HIT', 'Sanction Hit')], default='CLEAR', max_length=20)),
                ('synthetic_id_status', models.CharField(choices=[('CLEAN', 'Clean'), ('SUSPECT', 'Suspect')], default='CLEAN', max_length=20)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='cases.case')),
            ],
        ),
    ]
