# Generated by Django 6.0.3 on 2026-03-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='risk_level',
            field=models.CharField(default='LOW', max_length=20),
        ),
    ]
