# Generated by Django 5.2.11 on 2026-03-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=150)),
                ('agent_id', models.CharField(max_length=50)),
                ('agent_type', models.CharField(choices=[('DSA', 'DSA'), ('Broker', 'Broker'), ('Lead Partner', 'Lead Partner')], max_length=50)),
                ('total_amount_owed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('already_recovered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('emi_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction_day', models.CharField(choices=[('1st', '1st of month'), ('5th', '5th of month'), ('10th', '10th of month'), ('15th', '15th of month')], max_length=20)),
                ('reason', models.CharField(choices=[('Advance Clawback', 'Advance Clawback'), ('Overpayment', 'Overpayment'), ('Policy Breach', 'Policy Breach'), ('Dispute Recovery', 'Dispute Recovery'), ('Other', 'Other')], max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Cleared', 'Cleared'), ('Defaulted', 'Defaulted')], default='Active', max_length=20)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('cancel', models.BooleanField(default=False)),
                ('add_record', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
