# Generated by Django 5.2.11 on 2026-03-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayment_recovery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_owed', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('pending', models.IntegerField(default=0)),
                ('overall_recovery', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
