# Generated by Django 5.2.11 on 2026-03-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayment_recovery', '0002_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recovery_Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('all', 'All'), ('active', 'Active'), ('on_hold', 'On Hold'), ('cleared', 'Cleared'), ('defaulted', 'Defaulted')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
