# Generated by Django 5.2.11 on 2026-03-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayment_recovery', '0003_recovery_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('agent_id', models.CharField(max_length=50)),
                ('total_owed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recovered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('emi_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction_day', models.CharField(choices=[('1st', '1st'), ('5th', '5th'), ('10th', '10th'), ('15th', '15th')], max_length=10)),
                ('reason', models.CharField(choices=[('Overpayment', 'Overpayment'), ('Advance Clawback', 'Advance Clawback'), ('Policy Breach Fire', 'Policy Breach Fire'), ('Dispute Recovery', 'Dispute Recovery'), ('Other', 'Other')], max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Cleared', 'Cleared'), ('Defaulted', 'Defaulted'), ('On Hold', 'On Hold')], default='Active', max_length=20)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
