# Generated by Django 5.2.11 on 2026-03-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayment_recovery', '0004_editrecovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrecovery',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='editrecovery',
            name='save_cahnges',
            field=models.BooleanField(default=False),
        ),
    ]
