# Generated by Django 5.2.11 on 2026-03-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repayment_recovery', '0005_editrecovery_cancel_editrecovery_save_cahnges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editrecovery',
            old_name='save_cahnges',
            new_name='save_changes',
        ),
    ]
