# Generated by Django 6.0.1 on 2026-01-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartyuser',
            name='third_party_type',
            field=models.CharField(choices=[('VALUER', 'Valuer'), ('ADVISOR', 'Advisor'), ('CONSULTANT', 'Consultant')], max_length=20),
        ),
    ]
