# Generated by Django 5.2.12 on 2026-03-23 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionagent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('CUSTOMER_VISIT', 'Customer Visit'), ('RESIDENCE_VISIT', 'Residence Visit'), ('OFFICE_VISIT', 'Office Visit')], default='CUSTOMER_VISIT', max_length=30)),
                ('visit_outcome', models.CharField(choices=[('MET_DISCUSSED', 'Met & Discussed'), ('NOT_AVAILABLE', 'Not Available'), ('REFUSED_MEET', 'Refused to Meet'), ('ADDRESS_NOT_FOUND', 'Address Not Found')], max_length=30)),
                ('customer_met', models.BooleanField(default=True)),
                ('person_met', models.CharField(choices=[('SELF', 'Self (Customer)'), ('SPOUSE', 'Spouse'), ('FAMILY', 'Family Member'), ('NEIGHBOR', 'Neighbor'), ('SECURITY', 'Security/Watchman'), ('OTHER', 'Other')], default='SELF', max_length=20)),
                ('discussion_points', models.TextField()),
                ('next_action', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('is_within_range', models.BooleanField(default=False)),
                ('distance_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_recordings', to='collectionagent.collectionaccount')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_recordings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('house_exterior', 'House/Office Exterior'), ('customer_photo', 'Customer Photo'), ('address_proof', 'Address Proof'), ('meeting_proof', 'Meeting Proof')], max_length=30)),
                ('image', models.ImageField(upload_to='visit_photos/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='collectionagent.visitrecording')),
            ],
        ),
        migrations.CreateModel(
            name='VisitAudioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='visit_audio_recordings/')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_recordings', to='collectionagent.visitrecording')),
            ],
        ),
    ]
