# Generated by Django 5.2.12 on 2026-03-24 17:19

import collectionagent.recovery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionagent', '0002_visitrecording_visitphoto_visitaudiorecording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='collection_date',
            field=models.DateField(default=collectionagent.recovery.models.get_today),
        ),
    ]
