# Generated by Django 4.2.7 on 2025-11-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_collected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collector', models.CharField(max_length=100)),
                ('channel', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'collections',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=50, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tenure_months', models.IntegerField()),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DEFAULT', 'Default'), ('RESTRUCTURED', 'Restructured')], default='ACTIVE', max_length=30)),
                ('is_restructured', models.BooleanField(default=False)),
                ('closure_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'loan_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('BOUNCED', 'Bounced')], default='PENDING', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='lms.loanaccount')),
            ],
            options={
                'db_table': 'repayments',
                'ordering': ['-due_date'],
            },
        ),
    ]
