# Generated by Django 4.2.7 on 2025-11-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('los', '0001_initial'),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_account', to='los.loanapplication'),
        ),
        migrations.AddField(
            model_name='collection',
            name='loan_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='lms.loanaccount'),
        ),
    ]
