# Generated by Django 4.2.7 on 2025-11-21 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-collected_at']},
        ),
        migrations.AlterModelOptions(
            name='repayment',
            options={'ordering': ['-paid_at']},
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='amount_collected',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='date',
            new_name='collected_at',
        ),
        migrations.RenameField(
            model_name='loanaccount',
            old_name='loan',
            new_name='loan_application',
        ),
        migrations.RenameField(
            model_name='repayment',
            old_name='amount_due',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='closure_date',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='is_restructured',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='next_due_date',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='outstanding',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='principal_amount',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='status',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='tenure_months',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='status',
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='outstanding_principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='tenor_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='account_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='emi_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
