# Generated by Django 4.2.10 on 2026-03-24 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpanel_access_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalationmaster',
            name='escalation_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationmaster',
            name='escalation_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disbursementthirdparty',
            name='associated_stages',
            field=models.ManyToManyField(blank=True, to='adminpanel.disbursementstage'),
        ),
        migrations.AddField(
            model_name='disbursementdocument',
            name='applicable_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='adminpanel.disbursementstage'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.disbursementagency'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='down_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.downpayment'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='down_payment_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.disbursementstage'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.disbursementfrequency'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='required_documents',
            field=models.ManyToManyField(blank=True, to='adminpanel.disbursementdocument'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='third_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.disbursementthirdparty'),
        ),
        migrations.AddField(
            model_name='customisedtemplate',
            name='field_masters',
            field=models.ManyToManyField(blank=True, to='adminpanel.fieldmaster'),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('currency_code', 'isDeleted')},
        ),
        migrations.AddField(
            model_name='coupon',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='adminpanel.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='concessioncategory',
            name='linked_concession_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.concessiontype'),
        ),
        migrations.AddField(
            model_name='collectionaction',
            name='overdue_loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='adminpanel.overdueloan'),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='agent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.agenttype'),
        ),
        migrations.AddField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='adminpanel.organization'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_users', to='adminpanel_access_control.role'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='accounts.user'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('organization', 'branch_code')},
        ),
    ]
