# Generated by Django 4.2.7 on 2026-03-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExistingObligationManagement',
        ),
    ]
