# Generated by Django 4.2.7 on 2026-03-26 13:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_delete_existingobligationmanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObligationManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_status', models.CharField(max_length=100)),
                ('loan_performance', models.CharField(max_length=100)),
                ('card_type', models.CharField(max_length=100)),
                ('credit_card_status', models.CharField(max_length=100)),
                ('credit_card_performance', models.CharField(max_length=100)),
                ('total_loans', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Obligation Management',
                'verbose_name_plural': 'Obligation Managements',
                'db_table': 'admin_obligation_management',
            },
        ),
    ]
