# Generated by Django 4.2.7 on 2025-11-29 12:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_branch_options_remove_tenant_updated_at'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiintegration',
            options={},
        ),
        migrations.AlterModelOptions(
            name='webhooklog',
            options={},
        ),
        migrations.RenameField(
            model_name='apiintegration',
            old_name='headers_json',
            new_name='config',
        ),
        migrations.RenameField(
            model_name='apiintegration',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='apiintegration',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='apiintegration',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='webhooklog',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='webhooklog',
            name='integration',
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='event',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='apiintegration',
            name='provider',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterModelTable(
            name='apiintegration',
            table='integrations',
        ),
    ]
