# Generated by Django 4.2.7 on 2025-11-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rename_action_leadactivity_comment_customer_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeremployment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerkyc',
            name='customer',
        ),
        migrations.RenameField(
            model_name='leadactivity',
            old_name='comment',
            new_name='action',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='leadactivity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='leadactivity',
            name='next_followup',
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('CONVERTED', 'Converted')], default='NEW', max_length=50),
        ),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
        migrations.DeleteModel(
            name='CustomerEmployment',
        ),
        migrations.DeleteModel(
            name='CustomerKYC',
        ),
    ]
