# Generated by Django 4.2.7 on 2025-11-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_customeremployment_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(default='NEW', max_length=50),
        ),
    ]
