# Generated by Django 4.2.10 on 2026-03-24 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('tenant', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, default='', max_length=50)),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('supervisor_name', models.CharField(blank=True, default='', max_length=200)),
                ('supervisor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('supervisor_mobile', models.CharField(blank=True, default='', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, related_name='tenant_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='tenant_user_permissions_set', to='auth.permission')),
            ],
            options={
                'db_table': 'tenant_users',
            },
        ),
    ]
