# Generated by Django 5.2.9 on 2025-12-23 10:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_category', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=150, unique=True)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_tenure_months', models.PositiveIntegerField()),
                ('max_tenure_months', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('permissions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_type', models.CharField(max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interest_config', to='adminpanel.loanproduct')),
            ],
        ),
        migrations.CreateModel(
            name='FeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='adminpanel.loanproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ChargeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='adminpanel.loanproduct')),
            ],
        ),
        migrations.CreateModel(
            name='MasterAdminUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_master_admin', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoratoriumConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveIntegerField()),
                ('interest_waiver', models.BooleanField(default=False)),
                ('loan_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moratorium', to='adminpanel.loanproduct')),
            ],
        ),
        migrations.CreateModel(
            name='PenaltyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grace_days', models.PositiveIntegerField(default=0)),
                ('loan_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penalty', to='adminpanel.loanproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100)),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='adminpanel.loanproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('product_category', models.CharField(help_text='Loan / Credit', max_length=50)),
                ('product_type', models.CharField(help_text='Business Loan, Retail Loan, etc', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='product_mixes', to='adminpanel.loanproduct')),
            ],
        ),
        migrations.CreateModel(
            name='RepaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_type', models.CharField(max_length=30)),
                ('frequency', models.CharField(max_length=30)),
                ('installments', models.PositiveIntegerField()),
                ('loan_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repayment', to='adminpanel.loanproduct')),
            ],
        ),
    ]
