# Generated by Django 5.2.9 on 2025-12-24 08:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moratoriumconfig',
            old_name='interest_waiver',
            new_name='allowed',
        ),
        migrations.RemoveField(
            model_name='chargeconfig',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='feeconfig',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='moratoriumconfig',
            name='months',
        ),
        migrations.RemoveField(
            model_name='repaymentconfig',
            name='installments',
        ),
        migrations.AddField(
            model_name='chargeconfig',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feeconfig',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='moratoriumconfig',
            name='max_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productfacility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfacility',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productfacility',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productfacility',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chargeconfig',
            name='loan_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_configs', to='adminpanel.loanproduct'),
        ),
        migrations.AlterField(
            model_name='feeconfig',
            name='loan_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_configs', to='adminpanel.loanproduct'),
        ),
        migrations.AlterField(
            model_name='interestconfig',
            name='interest_type',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('FLOATING', 'Floating')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moratoriumconfig',
            name='loan_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moratorium_config', to='adminpanel.loanproduct'),
        ),
        migrations.AlterField(
            model_name='penaltyconfig',
            name='loan_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_config', to='adminpanel.loanproduct'),
        ),
        migrations.AlterField(
            model_name='penaltyconfig',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productfacility',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='product_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='product_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='repaymentconfig',
            name='frequency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='repaymentconfig',
            name='loan_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_config', to='adminpanel.loanproduct'),
        ),
        migrations.AlterField(
            model_name='repaymentconfig',
            name='repayment_type',
            field=models.CharField(choices=[('EMI', 'EMI'), ('BULLET', 'Bullet')], max_length=20),
        ),
    ]
