# Generated by Django 5.2.9 on 2025-12-24 13:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_permission_role_rolepermission_userrole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3'), ('L4', 'Level 4'), ('FINAL', 'Final')], max_length=10)),
                ('type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('TEAM', 'Team')], max_length=20)),
                ('product_type', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=150)),
                ('sanction_name', models.CharField(max_length=150)),
                ('rate_inc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rate_dec', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fees_inc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fees_dec', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tenure_inc', models.PositiveIntegerField(blank=True, null=True)),
                ('tenure_dec', models.PositiveIntegerField(blank=True, null=True)),
                ('moratorium_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moratorium_period', models.PositiveIntegerField(blank=True, null=True)),
                ('approval_range', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['level', 'product_type'],
            },
        ),
    ]
