# Generated by Django 5.2.9 on 2025-12-25 07:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_approvalmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_account_type', models.CharField(max_length=50)),
                ('average_banking_from', models.DateField()),
                ('average_banking_to', models.DateField()),
                ('average_banking_criteria', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applicant_type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('income_type', models.CharField(max_length=50)),
                ('other_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_receipt_mode', models.CharField(max_length=50)),
                ('update_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExistingObligationManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_status', models.CharField(max_length=50)),
                ('loan_performance', models.CharField(max_length=50)),
                ('card_type', models.CharField(max_length=50)),
                ('credit_card_status', models.CharField(max_length=50)),
                ('credit_card_performance', models.CharField(max_length=50)),
                ('total_loans', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCardManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('impact_type', models.CharField(max_length=50)),
                ('risk_impact', models.CharField(max_length=50)),
                ('professionals_config', models.JSONField(blank=True, null=True)),
                ('employees_config', models.JSONField(blank=True, null=True)),
                ('groups_config', models.JSONField(blank=True, null=True)),
                ('corporates_config', models.JSONField(blank=True, null=True)),
                ('others_config', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
