# Generated by Django 5.2.9 on 2025-12-25 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_bankingmanagement_eligibilitymanagement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptable_npa_percentage', models.PositiveIntegerField()),
                ('default_threshold_days', models.PositiveIntegerField()),
                ('default_trigger', models.CharField(max_length=100)),
                ('default_impact_score', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviationManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviation_type', models.CharField(max_length=100)),
                ('justification', models.TextField()),
                ('approving_authority', models.CharField(max_length=100)),
                ('impact_level', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FraudManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_category', models.CharField(max_length=100)),
                ('modus_operandi', models.TextField()),
                ('fraud_status', models.CharField(max_length=50)),
                ('reporting_authority', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('geo_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('borrower_segment_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('threshold_alerts', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskContainmentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcu_trigger', models.CharField(max_length=255)),
                ('investigation_status', models.CharField(max_length=50)),
                ('risk_type', models.CharField(max_length=50)),
                ('action_taken', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_category', models.CharField(max_length=100)),
                ('risk_parameter', models.CharField(max_length=255)),
                ('risk_severity', models.CharField(max_length=20)),
                ('risk_trigger_event', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
                ('parameter_value', models.CharField(max_length=255)),
                ('validity_from', models.DateField()),
                ('validity_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskMitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitigation_type', models.CharField(max_length=100)),
                ('mitigation_action', models.TextField()),
                ('effectiveness_score', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('associated_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.riskmanagement')),
            ],
        ),
    ]
