# Generated by Django 5.2.9 on 2025-12-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_defaultlimit_deviationmanagement_fraudmanagement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('notification_type', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=50)),
                ('importance', models.CharField(max_length=50)),
                ('notification_group', models.CharField(max_length=100)),
                ('target_audience', models.CharField(max_length=150)),
                ('template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=100)),
                ('report_name', models.CharField(max_length=150)),
                ('report_template', models.TextField()),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
