# Generated by Django 5.2.9 on 2025-12-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_notificationmaster_reportingmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='MISReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('auto', 'Auto Generated'), ('manual', 'Normal')], max_length=20)),
                ('report_name', models.CharField(max_length=200)),
                ('report_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ReportingMaster',
        ),
        migrations.RenameField(
            model_name='notificationmaster',
            old_name='frequency',
            new_name='importance_level',
        ),
        migrations.RenameField(
            model_name='notificationmaster',
            old_name='subject',
            new_name='notification_action',
        ),
        migrations.RenameField(
            model_name='notificationmaster',
            old_name='template',
            new_name='notification_template',
        ),
        migrations.RemoveField(
            model_name='notificationmaster',
            name='action_name',
        ),
        migrations.RemoveField(
            model_name='notificationmaster',
            name='importance',
        ),
        migrations.AddField(
            model_name='notificationmaster',
            name='notification_frequency',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationmaster',
            name='notification_subject',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationmaster',
            name='notification_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push Notification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationmaster',
            name='target_audience',
            field=models.CharField(max_length=200),
        ),
    ]
