# Generated by Django 4.2.7 on 2025-12-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_applicationprocess_coapplicant_geolocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanproduct',
            old_name='max_amount',
            new_name='product_amount',
        ),
        migrations.RenameField(
            model_name='loanproduct',
            old_name='max_tenure_months',
            new_name='product_period_value',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='min_amount',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='min_tenure_months',
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='product_facilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='product_period_unit',
            field=models.CharField(choices=[('Days', 'Days'), ('Months', 'Months'), ('Years', 'Years')], default='Months', max_length=10),
        ),
    ]
