# Generated by Django 4.2.7 on 2025-12-26 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_subscriptionplan_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promotion_name', models.CharField(max_length=100)),
                ('no_of_coupons', models.PositiveIntegerField()),
                ('coupon_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon_code', models.CharField(max_length=50, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('usage_status', models.CharField(choices=[('UNUSED', 'Unused'), ('USED', 'Used'), ('EXPIRED', 'Expired')], default='UNUSED', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='coupons', to='adminpanel.subscriptionplan')),
            ],
        ),
    ]
