# Generated by Django 4.2.7 on 2025-12-26 10:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_addresstype_agentcategory_agentconstitution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationAgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=150)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('verification_agent_type', models.CharField(max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.agentlocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=150)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('recovery_type', models.CharField(max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.agentlocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=150)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('agent_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.agentcategory')),
                ('agent_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.agentlevel')),
                ('agent_service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.agentservicetype')),
                ('agent_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.agenttype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.agentlocation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
