# Generated by Django 4.2.7 on 2025-12-29 07:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_verificationagency_collectionagent_channelpartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyVerificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agency_type', models.CharField(max_length=100)),
                ('verification_stage', models.CharField(max_length=100)),
                ('report_type', models.CharField(max_length=200)),
                ('turnaround_time', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfileRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=200)),
                ('parameter', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('impact_value', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollateralQualityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collateral_type', models.CharField(max_length=200)),
                ('ownership', models.CharField(max_length=100)),
                ('min_market_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_market_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('allowed_ltv', models.CharField(max_length=50)),
                ('risk_level', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditHistoryRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_bureau', models.CharField(max_length=100)),
                ('min_credit_score', models.IntegerField()),
                ('max_dpd_days', models.IntegerField()),
                ('max_enquiries', models.IntegerField()),
                ('risk_level', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialEligibilityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('income_type', models.CharField(max_length=100)),
                ('min_monthly_income', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_emi_ratio', models.CharField(max_length=50)),
                ('min_bank_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_existing_obligation', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeoLocationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('risk_level', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalScoreRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameter', models.CharField(max_length=200)),
                ('min_value', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=50)),
                ('risk_level', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalVerificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(max_length=100)),
                ('criteria', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskMitigationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_parameter', models.CharField(max_length=200)),
                ('mitigation_action', models.CharField(max_length=200)),
                ('severity', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=200)),
                ('rule_code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImpactValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('impact_type', models.CharField(max_length=50)),
                ('impact_value', models.CharField(max_length=100)),
                ('risk_impact', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.rulemaster')),
            ],
        ),
    ]
