# Generated by Django 4.2.7 on 2025-12-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_rename_max_amount_loanproduct_product_amount_and_more'),
        ('adminpanel', '0014_verificationagency_collectionagent_channelpartner'),
    ]

    operations = [
    ]
