# Generated by Django 4.2.7 on 2025-12-29 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpanel', '0015_agencyverificationrule_clientprofilerule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanImprovementRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_id', models.CharField(max_length=50)),
                ('improvement_type', models.CharField(choices=[('INTEREST_RATE', 'Change Interest Rate'), ('TENURE', 'Change Repayment Period'), ('EMI', 'Change EMI'), ('PRODUCT', 'Change Loan Product'), ('FEES', 'Change Fees & Charges'), ('COLLATERAL', 'Change Collateral'), ('RATIONALISATION', 'Repayment Rationalisation'), ('MORATORIUM', 'Moratorium of Interest'), ('TOP_UP', 'Top Up')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied')], default='PENDING', max_length=20)),
                ('effective_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_improvements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revised_topup_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('required_vintage', models.PositiveIntegerField()),
                ('vintage_unit', models.CharField(max_length=10)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.loanimprovementrequest')),
            ],
        ),
        migrations.CreateModel(
            name='TenureChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_tenure', models.PositiveIntegerField()),
                ('revised_tenure', models.PositiveIntegerField()),
                ('tenure_unit', models.CharField(default='MONTHS', max_length=10)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.loanimprovementrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RepaymentRationalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationalisation_type', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('duration_unit', models.CharField(max_length=10)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.loanimprovementrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ProductChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_product', models.CharField(max_length=100)),
                ('new_product', models.CharField(max_length=100)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.loanimprovementrequest')),
            ],
        ),
        migrations.CreateModel(
            name='InterestRateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('revised_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.loanimprovementrequest')),
            ],
        ),
        migrations.CreateModel(
            name='InterestMoratorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moratorium_period', models.PositiveIntegerField()),
                ('period_unit', models.CharField(max_length=10)),
                ('revised_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.loanimprovementrequest')),
            ],
        ),
        migrations.CreateModel(
            name='FeeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=100)),
                ('old_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revised_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.loanimprovementrequest')),
            ],
        ),
        migrations.CreateModel(
            name='EMIChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_emi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revised_emi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.loanimprovementrequest')),
            ],
        ),
        migrations.CreateModel(
            name='CollateralChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_collateral_type', models.CharField(max_length=100)),
                ('revised_collateral_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.loanimprovementrequest')),
            ],
        ),
    ]
