# Generated by Django 4.2.7 on 2025-12-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_merge_20251227_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='module',
            field=models.CharField(default='core', help_text='Module name like users, audit, loans, reports', max_length=50),
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
