# Generated by Django 4.2.7 on 2025-12-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_permission_module_alter_permission_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='module',
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(),
        ),
    ]
