# Generated by Django 4.2.7 on 2025-12-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_loanimprovementrequest_topuprequest_tenurechange_and_more'),
        ('adminpanel', '0017_remove_permission_module_and_more'),
    ]

    operations = [
    ]
