# Generated by Django 4.2.7 on 2025-12-29 13:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_merge_20251229_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcessionType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concession_type_name', models.CharField(max_length=150)),
                ('applicable_on', models.CharField(choices=[('Sanction', 'Sanction'), ('Disbursement', 'Disbursement'), ('Repayment', 'Repayment')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_user', models.CharField(max_length=100)),
                ('modified_user', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'concession_type',
            },
        ),
        migrations.CreateModel(
            name='ConcessionCategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=150)),
                ('product_type', models.CharField(max_length=100)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('eligibility_criteria', models.TextField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_user', models.CharField(max_length=100)),
                ('modified_user', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('linked_concession_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.concessiontype')),
            ],
            options={
                'db_table': 'concession_category',
            },
        ),
    ]
