# Generated by Django 4.2.7 on 2025-12-29 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_concessiontype_concessioncategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency_code', models.CharField(max_length=10)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('conversion_value_to_inr', models.DecimalField(decimal_places=6, max_digits=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_user', models.CharField(max_length=100)),
                ('modified_user', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'currency_management',
                'unique_together': {('currency_code', 'isDeleted')},
            },
        ),
    ]
