# Generated by Django 4.2.7 on 2025-12-29 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=100)),
                ('incentive_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condition', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classification_name', models.CharField(max_length=100)),
                ('classification_type', models.CharField(choices=[('STANDARD', 'Standard'), ('SUBSTANDARD', 'Substandard'), ('NPA', 'NPA')], max_length=20)),
                ('criteria_description', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProvisioningNPA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classification_type', models.CharField(max_length=50)),
                ('days_overdue', models.PositiveIntegerField()),
                ('provision_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SettlementRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('settlement_policy_name', models.CharField(max_length=150)),
                ('max_discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WriteOffRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('writeoff_policy', models.CharField(max_length=150)),
                ('minimum_days_overdue', models.PositiveIntegerField()),
                ('product_type', models.CharField(max_length=100)),
            ],
        ),
    ]
