# Generated by Django 4.2.7 on 2025-12-29 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_incentivemanagement_loanclassification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAgentMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=150)),
                ('agent_name', models.CharField(max_length=150)),
                ('mapping_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], max_length=20)),
                ('region', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientTeamMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=150)),
                ('team_name', models.CharField(max_length=150)),
                ('mapping_start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_collection_types', models.JSONField()),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash_collection_limit', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(max_length=255)),
                ('transaction_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mode', models.CharField(choices=[('TEST', 'Test'), ('LIVE', 'Live')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_type', models.CharField(choices=[('AGENT', 'Agent'), ('PARTNER', 'Partner')], max_length=20)),
                ('agent_or_partner_name', models.CharField(max_length=150)),
                ('payout_cycle', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
