# Generated by Django 4.2.7 on 2025-12-29 19:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0022_clientagentmapping_clientteammapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisbursementAgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=150)),
                ('agency_type', models.CharField(max_length=100)),
                ('contact_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DisbursementFrequency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency_label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DisbursementStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DownPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('refundable', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DisbursementThirdParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('third_party_name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('contact_information', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=10)),
                ('associated_stages', models.ManyToManyField(blank=True, to='adminpanel.disbursementstage')),
            ],
        ),
        migrations.CreateModel(
            name='DisbursementDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=150)),
                ('document_type', models.CharField(max_length=100)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=10)),
                ('applicable_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='adminpanel.disbursementstage')),
            ],
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disbursement_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=10)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.disbursementagency')),
                ('down_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.downpayment')),
                ('down_payment_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.disbursementstage')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.disbursementfrequency')),
                ('required_documents', models.ManyToManyField(blank=True, to='adminpanel.disbursementdocument')),
                ('third_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.disbursementthirdparty')),
            ],
        ),
    ]
