# Generated by Django 4.2.7 on 2025-12-29 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_disbursementagency_disbursementfrequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollateralDocument',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collateral_category', models.CharField(max_length=100)),
                ('collateral_type', models.CharField(max_length=100)),
                ('security_coverage_type', models.CharField(max_length=100)),
                ('mode_of_collateral', models.CharField(max_length=100)),
                ('collateral_details', models.TextField()),
                ('loan_to_collateral_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_user', models.CharField(max_length=100)),
                ('modified_user', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'collateral_documents',
            },
        ),
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=150)),
                ('requirement_type', models.CharField(max_length=100)),
                ('requirement_stage', models.CharField(max_length=100)),
                ('requirement_mode', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_user', models.CharField(max_length=100)),
                ('modified_user', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'loan_documents',
            },
        ),
        migrations.CreateModel(
            name='SanctionDocument',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=150)),
                ('requirement_type', models.CharField(max_length=100)),
                ('requirement_stage', models.CharField(max_length=100)),
                ('requirement_mode', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_user', models.CharField(max_length=100)),
                ('modified_user', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sanction_documents',
            },
        ),
    ]
