# Generated by Django 4.2.7 on 2025-12-29 20:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0024_collateraldocument_loandocument_sanctiondocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('contact_person', models.CharField(max_length=150)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cin_number', models.CharField(blank=True, max_length=30, null=True)),
                ('full_address', models.TextField()),
                ('loan_products', models.TextField(help_text='Comma separated loan products')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(max_length=100)),
                ('branch_code', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=150)),
                ('branch_address', models.TextField()),
                ('contact_person', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='adminpanel.organization')),
            ],
            options={
                'unique_together': {('organization', 'branch_code')},
            },
        ),
    ]
