# Generated by Django 4.2.7 on 2025-12-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0025_organization_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofilerule',
            name='created_by',
            field=models.CharField(default='System', max_length=100),
        ),
        migrations.AddField(
            model_name='clientprofilerule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clientprofilerule',
            name='updated_by',
            field=models.CharField(default='System', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscription_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], max_length=20),
        ),
    ]
