# Generated by Django 4.2.7 on 2025-12-30 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_dashboardactivity_dashboardalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentTypeMaster',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100, unique=True)),
                ('created_user', models.CharField(max_length=100)),
                ('modified_user', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'employment_type_master',
                'ordering': ['emp_name'],
            },
        ),
        migrations.CreateModel(
            name='OccupationTypeMaster',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occ_name', models.CharField(max_length=100, unique=True)),
                ('created_user', models.CharField(max_length=100)),
                ('modified_user', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'occupation_type_master',
                'ordering': ['occ_name'],
            },
        ),
    ]
