# Generated by Django 4.2.7 on 2025-12-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_clientprofilerule_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofilerule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='clientprofilerule',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='clientprofilerule',
            name='updated_by',
        ),
    ]
