# Generated by Django 4.2.7 on 2025-12-31 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0027_employmenttypemaster_occupationtypemaster'),
        ('adminpanel', '0027_remove_clientprofilerule_created_by_and_more'),
    ]

    operations = [
    ]
