# Generated by Django 4.2.7 on 2025-12-31 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0028_merge_20251231_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelpartner',
            name='agent_category',
        ),
        migrations.RemoveField(
            model_name='channelpartner',
            name='agent_level',
        ),
        migrations.RemoveField(
            model_name='channelpartner',
            name='agent_service_type',
        ),
        migrations.RemoveField(
            model_name='channelpartner',
            name='location',
        ),
        migrations.RemoveField(
            model_name='collectionagent',
            name='location',
        ),
        migrations.RemoveField(
            model_name='verificationagency',
            name='location',
        ),
    ]
