# Generated by Django 4.2.7 on 2025-12-31 08:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0028_merge_20251231_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_category', models.CharField(max_length=50)),
                ('client_type', models.CharField(max_length=50)),
                ('constitution', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=50)),
                ('applicant_type', models.CharField(max_length=50)),
                ('employment_type', models.CharField(max_length=50)),
                ('employment_category', models.CharField(max_length=50)),
                ('employer_type', models.CharField(max_length=50)),
                ('employer', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=50)),
                ('occupation_type', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=100)),
                ('mode_of_occupation', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=100)),
                ('membership_type', models.CharField(max_length=100)),
                ('gender_salute', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=50)),
                ('address_type', models.CharField(max_length=50)),
                ('ownership', models.CharField(max_length=50)),
                ('employee_quota', models.CharField(max_length=50)),
                ('group_loans', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_type', models.CharField(max_length=50)),
                ('vendor_category', models.CharField(max_length=50)),
                ('vendor_constitution', models.CharField(max_length=50)),
                ('vendor_location', models.CharField(max_length=100)),
                ('vendor_service_type', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AddressType',
        ),
        migrations.DeleteModel(
            name='ApplicantType',
        ),
        migrations.DeleteModel(
            name='ClientCategory',
        ),
        migrations.DeleteModel(
            name='ClientConstitution',
        ),
        migrations.DeleteModel(
            name='ClientRole',
        ),
        migrations.DeleteModel(
            name='ClientType',
        ),
        migrations.DeleteModel(
            name='EmployeeQuota',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='EmploymentCategory',
        ),
        migrations.DeleteModel(
            name='EmploymentType',
        ),
        migrations.DeleteModel(
            name='GenderSalutation',
        ),
        migrations.DeleteModel(
            name='GroupLoan',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='MembershipType',
        ),
        migrations.DeleteModel(
            name='ModeOfOccupation',
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
        migrations.DeleteModel(
            name='OccupationType',
        ),
        migrations.DeleteModel(
            name='Ownership',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.DeleteModel(
            name='VendorCategory',
        ),
        migrations.DeleteModel(
            name='VendorConstitution',
        ),
        migrations.DeleteModel(
            name='VendorLocation',
        ),
        migrations.DeleteModel(
            name='VendorServiceType',
        ),
        migrations.DeleteModel(
            name='VendorType',
        ),
        migrations.RemoveField(
            model_name='agentcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agentcategory',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='agentcategory',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='agentcategory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='agentconstitution',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agentconstitution',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='agentconstitution',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='agentconstitution',
            name='status',
        ),
        migrations.RemoveField(
            model_name='agentlevel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agentlevel',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='agentlevel',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='agentlevel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='agentlocation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agentlocation',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='agentlocation',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='agentlocation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='agentresponsibility',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agentresponsibility',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='agentresponsibility',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='agentresponsibility',
            name='status',
        ),
        migrations.RemoveField(
            model_name='agentservicetype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agentservicetype',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='agentservicetype',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='agentservicetype',
            name='status',
        ),
        migrations.RemoveField(
            model_name='agenttype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agenttype',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='agenttype',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='agenttype',
            name='status',
        ),
        migrations.AlterField(
            model_name='agentcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='agentcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agentconstitution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='agentconstitution',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agentlevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='agentlevel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agentlocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='agentresponsibility',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='agentservicetype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='agenttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='agenttype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.agentcategory'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_constitution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.agentconstitution'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.agentlevel'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.agentlocation'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_responsibility',
            field=models.ManyToManyField(to='adminpanel.agentresponsibility'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.agentservicetype'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.agenttype'),
        ),
    ]
