# Generated by Django 4.2.7 on 2025-12-31 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0029_agentprofile_clientprofile_vendorprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorConstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='VendorServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='VendorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.vendorcategory'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_constitution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.vendorconstitution'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.vendorlocation'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.vendorservicetype'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.vendortype'),
        ),
    ]
