# Generated by Django 4.2.7 on 2025-12-31 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0029_remove_channelpartner_agent_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
