# Generated by Django 4.2.7 on 2025-12-31 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0028_merge_20251231_1140'),
        ('adminpanel', '0030_disbursement_created_at'),
    ]

    operations = [
    ]
