# Generated by Django 4.2.7 on 2025-12-31 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0030_vendorcategory_vendorconstitution_vendorlocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientConstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenderSalute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModeOfOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OccupationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='employee_quota',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='group_loans',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='agentcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentconstitution',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentlevel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentresponsibility',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentservicetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agenttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorconstitution',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorlocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorservicetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agentcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='agentconstitution',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='agentlevel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='agentlocation',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='agentresponsibility',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='agentservicetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='agenttype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='employer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendorlocation',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendorservicetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='address_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.addresstype'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='applicant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.applicanttype'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='client_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.clientcategory'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='client_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.clienttype'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='constitution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.clientconstitution'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='employer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.employertype'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='employment_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.employmentcategory'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='employment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.employmenttype'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='gender_salute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.gendersalute'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.industry'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.institution'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='membership_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.membershiptype'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='mode_of_occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.modeofoccupation'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.occupation'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='occupation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.occupationtype'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='ownership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.ownership'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.qualification'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.relationship'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.clientrole'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.sector'),
        ),
    ]
