# Generated by Django 4.2.7 on 2025-12-31 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0031_addresstype_applicanttype_clientcategory_and_more'),
        ('adminpanel', '0031_merge_20251231_1629'),
    ]

    operations = [
    ]
