# Generated by Django 4.2.7 on 2026-01-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0035_adminuser_branch_adminuser_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='organization',
        ),
    ]
