# Generated by Django 4.2.7 on 2026-01-06 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0037_approvalassignment_escalationmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargeconfig',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='feeconfig',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='product_facilities',
        ),
        migrations.RemoveField(
            model_name='moratoriumconfig',
            name='allowed',
        ),
        migrations.RemoveField(
            model_name='moratoriumconfig',
            name='max_months',
        ),
        migrations.RemoveField(
            model_name='penaltyconfig',
            name='grace_days',
        ),
        migrations.RemoveField(
            model_name='penaltyconfig',
            name='penalty_rate',
        ),
        migrations.RemoveField(
            model_name='productfacility',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productfacility',
            name='is_mandatory',
        ),
        migrations.AddField(
            model_name='chargeconfig',
            name='frequency',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chargeconfig',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='chargeconfig',
            name='recovery_stage',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeconfig',
            name='frequency',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeconfig',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feeconfig',
            name='recovery_mode',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeconfig',
            name='recovery_stage',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interestconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moratoriumconfig',
            name='moratorium_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moratoriumconfig',
            name='period_unit',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moratoriumconfig',
            name='period_value',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penaltyconfig',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='penaltyconfig',
            name='recovery_stage',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repaymentconfig',
            name='no_of_repayments',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chargeconfig',
            name='loan_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='adminpanel.loanproduct'),
        ),
        migrations.AlterField(
            model_name='feeconfig',
            name='loan_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='adminpanel.loanproduct'),
        ),
        migrations.AlterField(
            model_name='interestconfig',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='interestconfig',
            name='loan_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interest', to='adminpanel.loanproduct'),
        ),
        migrations.AlterField(
            model_name='moratoriumconfig',
            name='loan_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moratorium', to='adminpanel.loanproduct'),
        ),
        migrations.AlterField(
            model_name='penaltyconfig',
            name='loan_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penalty', to='adminpanel.loanproduct'),
        ),
        migrations.AlterField(
            model_name='repaymentconfig',
            name='loan_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repayment', to='adminpanel.loanproduct'),
        ),
        migrations.AlterField(
            model_name='repaymentconfig',
            name='repayment_type',
            field=models.CharField(max_length=50),
        ),
    ]
