# Generated by Django 4.2.7 on 2026-01-06 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0038_remove_chargeconfig_amount_remove_feeconfig_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fees_frequency', models.CharField(choices=[('ONE_TIME', 'One-time'), ('MONTHLY', 'Monthly'), ('ANNUALLY', 'Annually')], max_length=20)),
                ('basis_of_fees', models.CharField(choices=[('FIXED', 'Fixed'), ('PERCENTAGE', 'Percentage'), ('SLAB', 'Slab-based')], max_length=20)),
                ('fees_recovery_stage', models.CharField(choices=[('DISBURSEMENT', 'Disbursement'), ('ONGOING', 'Ongoing'), ('CLOSURE', 'Closure')], max_length=20)),
                ('fees_recovery_mode', models.CharField(choices=[('DIRECT_DEBIT', 'Direct Debit'), ('AUTO_DEBIT', 'Auto-debit'), ('CASH', 'Cash')], max_length=20)),
                ('fees_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fees',
                'ordering': ['-created_at'],
            },
        ),
    ]
