# Generated by Django 4.2.7 on 2026-01-06 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0039_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One-time'), ('RECURRING', 'Recurring')], max_length=20)),
                ('basis_of_recovery', models.CharField(choices=[('FIXED', 'Fixed'), ('SLAB', 'Slab'), ('VARIABLE', 'Variable')], max_length=20)),
                ('recovery_stage', models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('POST_DISBURSEMENT', 'Post-disbursement')], max_length=30)),
                ('recovery_mode', models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual')], max_length=20)),
                ('rate_of_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'charges',
                'ordering': ['-created_at'],
            },
        ),
    ]
