# Generated by Django 4.2.7 on 2026-01-06 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0040_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('benchmark_type', models.CharField(choices=[('MCLR', 'MCLR'), ('RBI_RATE', 'RBI Rate'), ('BASE_RATE', 'Base Rate')], max_length=30)),
                ('benchmark_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=20)),
                ('benchmark_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mark_up', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_type', models.CharField(choices=[('FIXED', 'Fixed'), ('FLOATING', 'Floating')], max_length=20)),
                ('accrual_stage', models.CharField(choices=[('PRE_EMI', 'Pre-EMI'), ('POST_EMI', 'Post-EMI')], max_length=20)),
                ('accrual_method', models.CharField(choices=[('SIMPLE', 'Simple'), ('COMPOUND', 'Compound')], max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Interest Rate (% per annum)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interest_configurations',
                'ordering': ['-created_at'],
            },
        ),
    ]
