# Generated by Django 4.2.7 on 2026-01-06 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0041_interestconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repayment_type', models.CharField(choices=[('EMI', 'EMI'), ('BULLET', 'Bullet'), ('STEP_UP', 'Step-up')], max_length=20)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('BI_WEEKLY', 'Bi-weekly')], max_length=20)),
                ('limit_in_month', models.PositiveIntegerField(help_text='Total months of repayment')),
                ('gap_between_disbursement_and_first_repayment', models.PositiveIntegerField(help_text='Gap (in months) between disbursement and first repayment')),
                ('number_of_repayments', models.PositiveIntegerField(help_text='Total number of installments')),
                ('sequence_of_repayment_adjustment', models.CharField(choices=[('PRINCIPAL_FIRST', 'Principal First'), ('INTEREST_FIRST', 'Interest First')], max_length=30)),
                ('repayment_months', models.JSONField(default=list, help_text='Allowed repayment months (e.g. Jan, Feb)')),
                ('repayment_days', models.JSONField(default=list, help_text='Allowed days of the week (e.g. Monday)')),
                ('repayment_dates', models.JSONField(default=list, help_text='Allowed dates (e.g. 1st, 5th, 10th)')),
                ('mode_of_collection', models.CharField(choices=[('NACH', 'NACH'), ('CASH', 'Cash'), ('ONLINE', 'Online')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'repayment_configurations',
                'ordering': ['-created_at'],
            },
        ),
    ]
