# Generated by Django 4.2.7 on 2026-01-06 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0042_repaymentconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('penalty_name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One-time'), ('RECURRING', 'Recurring')], max_length=20)),
                ('basis_of_recovery', models.CharField(choices=[('FIXED', 'Fixed'), ('PERCENTAGE', 'Percentage'), ('SLAB', 'Slab')], max_length=20)),
                ('recovery_stage', models.CharField(choices=[('MISSED_EMI', 'Missed EMI'), ('POST_DEFAULT', 'Post Default')], max_length=30)),
                ('recovery_mode', models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual')], max_length=20)),
                ('rate_of_penalty', models.DecimalField(decimal_places=2, help_text='Penalty amount or percentage', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'penalties',
                'ordering': ['-created_at'],
            },
        ),
    ]
