# Generated by Django 4.2.7 on 2026-01-06 10:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0043_penalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moratorium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moratorium_type', models.CharField(choices=[('FULL', 'Full'), ('INTEREST_ONLY', 'Interest-only')], max_length=20)),
                ('period_value', models.PositiveIntegerField(help_text='Duration value of moratorium')),
                ('period_unit', models.CharField(choices=[('DAY', 'Day'), ('MONTH', 'Month')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount under moratorium', max_digits=14)),
                ('effect_of_moratorium', models.CharField(choices=[('INTEREST_ONLY', 'Interest-only'), ('DEFERRED', 'Deferred')], max_length=20)),
                ('interest_rationalisation', models.BooleanField(default=False, help_text='If interest is waived during moratorium')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'moratoriums',
                'ordering': ['-created_at'],
            },
        ),
    ]
