# Generated by Django 4.2.7 on 2026-01-06 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0044_moratorium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_category', models.CharField(help_text='Broad classification (e.g., Loan, Credit)', max_length=100)),
                ('product_type', models.CharField(help_text='Sub-category or variant (e.g., Personal Loan, Home Loan)', max_length=100)),
                ('product_name', models.CharField(help_text='Name of the specific product', max_length=150, unique=True)),
                ('product_period_value', models.PositiveIntegerField(help_text='Tenure value')),
                ('product_period_unit', models.CharField(choices=[('DAYS', 'Days'), ('MONTHS', 'Months'), ('YEARS', 'Years')], help_text='Tenure unit', max_length=10)),
                ('product_amount', models.DecimalField(decimal_places=2, help_text='Loan amount or service value', max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='feeconfig',
            name='loan_product',
        ),
        migrations.RemoveField(
            model_name='interestconfig',
            name='loan_product',
        ),
        migrations.RemoveField(
            model_name='moratoriumconfig',
            name='loan_product',
        ),
        migrations.RemoveField(
            model_name='penaltyconfig',
            name='loan_product',
        ),
        migrations.RemoveField(
            model_name='productfacility',
            name='loan_product',
        ),
        migrations.RemoveField(
            model_name='repaymentconfig',
            name='loan_product',
        ),
        migrations.AlterModelOptions(
            name='productmix',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='productmix',
            name='name',
        ),
        migrations.AddField(
            model_name='productmix',
            name='product_mix_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Combined price / amount of product mix', max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmix',
            name='product_mix_name',
            field=models.CharField(default=0, help_text='Unique name for product mix', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmix',
            name='product_period_unit',
            field=models.CharField(choices=[('DAYS', 'Days'), ('MONTHS', 'Months'), ('YEARS', 'Years')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmix',
            name='product_period_value',
            field=models.PositiveIntegerField(default=0, help_text='Duration value of product mix'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmix',
            name='product_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='productmix',
            table='product_mixes',
        ),
        migrations.DeleteModel(
            name='ChargeConfig',
        ),
        migrations.DeleteModel(
            name='FeeConfig',
        ),
        migrations.DeleteModel(
            name='InterestConfig',
        ),
        migrations.DeleteModel(
            name='LoanProduct',
        ),
        migrations.DeleteModel(
            name='MoratoriumConfig',
        ),
        migrations.DeleteModel(
            name='PenaltyConfig',
        ),
        migrations.DeleteModel(
            name='ProductFacility',
        ),
        migrations.DeleteModel(
            name='RepaymentConfig',
        ),
        migrations.AlterField(
            model_name='productmix',
            name='products',
            field=models.ManyToManyField(help_text='Base products included in this mix', related_name='product_mixes', to='adminpanel.product'),
        ),
    ]
