# Generated by Django 4.2.7 on 2026-01-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0038_alter_adminuser_role'),
        ('adminpanel', '0045_product_remove_feeconfig_loan_product_and_more'),
    ]

    operations = [
    ]
