# Generated by Django 4.2.7 on 2026-01-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0045_product_remove_feeconfig_loan_product_and_more'),
    ]

    operations = [
    ]
