# Generated by Django 4.2.7 on 2026-01-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0038_alter_adminuser_role'),
        ('adminpanel', '0046_merge_20260108_1137'),
    ]

    operations = [
    ]
