# Generated by Django 4.2.7 on 2026-01-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0046_merge_20260107_1712'),
        ('adminpanel', '0047_merge_20260108_1214'),
    ]

    operations = [
    ]
