# Generated by Django 4.2.7 on 2026-01-08 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
        ('adminpanel', '0048_merge_20260109_0324'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='role',
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_users', to='access_control.role'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
