# Generated by Django 4.2.7 on 2026-01-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0048_merge_20260108_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankAccountType',
        ),
        migrations.AddField(
            model_name='bank',
            name='account_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
