# Generated by Django 4.2.7 on 2026-01-08 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0049_delete_bankaccounttype_bank_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeOfBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('PAYMENT', 'Payment')], max_length=10)),
                ('mode_name', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ModeOfTransaction',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='account_type',
            new_name='bank_account_type',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='businessmodel',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='fundtype',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_allocation_logic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='banks',
            field=models.ManyToManyField(related_name='portfolios', to='adminpanel.bank'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
