# Generated by Django 4.2.7 on 2026-01-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0049_alter_rolepermission_unique_together_and_more'),
        ('adminpanel', '0050_modeofbank_delete_modeoftransaction_and_more'),
    ]

    operations = [
    ]
