# Generated by Django 4.2.7 on 2026-01-09 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0051_remove_agentcategory_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_key', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredefinedTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomisedTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('template_type', models.CharField(choices=[('LEGAL', 'Legal'), ('FINANCIAL', 'Financial'), ('AGREEMENT', 'Agreement')], max_length=50)),
                ('template_purpose', models.TextField()),
                ('is_mandatory', models.BooleanField(default=False)),
                ('requirement_notes', models.TextField(blank=True, null=True)),
                ('field_masters', models.ManyToManyField(blank=True, to='adminpanel.fieldmaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
