# Generated by Django 4.2.7 on 2026-01-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0051_merge_20260109_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalassignment',
            name='user_or_group',
        ),
        migrations.AddField(
            model_name='approvalassignment',
            name='approver_type',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='approvalassignment',
            name='group_users',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalassignment',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
