# Generated by Django 4.2.7 on 2026-01-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0046_merge_20260107_2056'),
        ('adminpanel', '0049_alter_rolepermission_unique_together_and_more'),
        ('adminpanel', '0052_fieldmaster_predefinedtemplate_customisedtemplate'),
    ]

    operations = [
    ]
