# Generated by Django 4.2.7 on 2026-01-09 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpanel', '0052_remove_approvalassignment_user_or_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalassignment',
            name='approver_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group')], max_length=20),
        ),
        migrations.AlterField(
            model_name='escalationmaster',
            name='escalation_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escalationmaster',
            name='escalation_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
