# Generated by Django 4.2.7 on 2026-01-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0053_alter_approvalassignment_approver_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalassignment',
            name='approver_type',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group')], max_length=20, null=True),
        ),
    ]
