# Generated by Django 4.2.7 on 2026-01-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0052_fieldmaster_predefinedtemplate_customisedtemplate'),
        ('adminpanel', '0054_alter_approvalassignment_approver_type'),
    ]

    operations = [
    ]
