# Generated by Django 4.2.7 on 2026-01-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0053_merge_20260109_1856'),
        ('adminpanel', '0056_alter_fund_fund_type'),
    ]

    operations = [
    ]
