# Generated by Django 4.2.7 on 2026-02-27 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('client', 'Client'), ('employer', 'Employer'), ('partner', 'Partner'), ('vendor', 'Vendor')], max_length=20)),
                ('industry', models.CharField(choices=[('banking', 'Banking'), ('retail', 'Retail'), ('services', 'Services'), ('manufacturing', 'Manufacturing'), ('technology', 'Technology'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('real_estate', 'Real Estate'), ('other', 'Other')], max_length=30)),
                ('gst_number', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('TASK', 'Task'), ('MEETING', 'Meeting')], max_length=10)),
                ('task_type', models.CharField(blank=True, choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('REMINDER', 'Reminder')], max_length=20, null=True)),
                ('task_title', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], max_length=10)),
                ('due_datetime', models.DateTimeField()),
                ('remind_before', models.CharField(blank=True, choices=[('15_MIN', '15 minutes before'), ('30_MIN', '30 minutes before'), ('1_HOUR', '1 hour before'), ('1_DAY', '1 day before'), ('2_DAY', '2 days before')], max_length=20, null=True)),
                ('assigned_to', models.CharField(choices=[('AGENT_A', 'Agent A'), ('AGENT_B', 'Agent B'), ('AGENT_C', 'Agent C')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('campaign', 'Campaign'), ('website', 'Website'), ('referral', 'Referral'), ('walkin', 'Walk-in')], max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('assigned_to', models.CharField(choices=[('agent_a', 'Agent A'), ('agent_b', 'Agent B'), ('agent_c', 'Agent C')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('IN_PERSON', 'In-Person'), ('VIDEO_CALL', 'Video Call'), ('PHONE_CALL', 'Phone Call')], max_length=20)),
                ('meeting_mode', models.CharField(choices=[('ZOOM', 'Zoom'), ('GOOGLE_MEET', 'Google Meet'), ('WHATSAPP', 'Whatsapp'), ('PHYSICAL', 'Physical')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '1 hour'), (90, '1.5 hours'), (120, '2 hours')])),
                ('link', models.URLField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('agenda', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
