# Generated by Django 4.2.7 on 2026-02-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecrm', '0001_initial'),
        ('data_lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_lead.lead'),
        ),
        migrations.AddField(
            model_name='activity',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='data_lead.lead'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to='corecrm.account'),
        ),
    ]
