# Generated by Django 4.2.10 on 2026-03-24 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internaluserrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalrole',
            name='dashboards',
            field=models.ManyToManyField(blank=True, to='internal.internaldashboard'),
        ),
        migrations.AddField(
            model_name='internalrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='internal.internalpermission'),
        ),
        migrations.AddField(
            model_name='internalpermission',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='internal.internaldashboard'),
        ),
        migrations.AlterUniqueTogether(
            name='internaluserrole',
            unique_together={('user', 'role')},
        ),
    ]
