# Generated by Django 4.2.7 on 2026-02-27 13:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_status', models.CharField(choices=[('All', 'All'), ('HOT', 'Hot Lead'), ('SLA_BREACH', 'SLA Breach'), ('DOCS_PENDING', 'Documents Pending'), ('AVG_INTENT', 'Average Intent')], default='HOT', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('lead_source', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField(default=0)),
                ('intent_percentage', models.IntegerField(default=0)),
                ('docs_completed', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('FOLLOW_UP', 'Follow Up'), ('MEETING', 'Meeting Scheduled'), ('QUALIFIED', 'Qualified'), ('DEAL', 'Converted to Deal'), ('DORMANT', 'Dormant')], default='NEW', max_length=20)),
                ('los_stage', models.CharField(default='Stage 4', max_length=50)),
                ('los_description', models.TextField(default='Verified via KYC & Income Documents')),
                ('los_status', models.CharField(default='Pre-Approved', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sla_days', models.IntegerField(default=2)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='hot_lead.stage')),
            ],
        ),
        migrations.CreateModel(
            name='IntentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('WHATSAPP_CLICK', 'WhatsApp Link Clicked'), ('EXPLICIT_REQUEST', 'Explicit Request'), ('VIEWED_DOC', 'Viewed Loan Terms')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='hot_lead.hotlead')),
            ],
        ),
        migrations.AddField(
            model_name='hotlead',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hot_lead', to='hot_lead.lead'),
        ),
    ]
