# Generated by Django 4.2.7 on 2026-03-06 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_leads', models.BooleanField(default=False, help_text='User has opted in to export their leads data.')),
                ('export_reports', models.BooleanField(default=False, help_text='User has opted in to export their reports data.')),
                ('leads_last_exported_at', models.DateTimeField(blank=True, null=True)),
                ('reports_last_exported_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
