# Generated by Django 4.2.7 on 2026-01-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='created_by',
        ),
    ]
