# Generated by Django 4.2.7 on 2026-02-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_status_ticket_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('TECHNICAL', 'Technical Issue'), ('PAYMENT', 'Payment Issue'), ('REPAYMENT', 'Repayment Issue'), ('ACCOUNT', 'Account Issue'), ('DISPUTE', 'Dispute'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20),
        ),
    ]
