# Generated by Django 6.0.2 on 2026-02-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_id', models.CharField(max_length=20, unique=True)),
                ('agreement_type', models.CharField(choices=[('Loan Agreement', 'Loan Agreement'), ('Collateral Agreement', 'Collateral Agreement'), ('Guarantor Agreement', 'Guarantor Agreement')], max_length=50)),
                ('client_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('assigned_to', models.CharField(choices=[('Rahul', 'Rahul'), ('Amit', 'Amit'), ('Sneha', 'Sneha'), ('Priya', 'Priya')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submitted_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
