# Generated by Django 6.0.2 on 2026-02-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agreement_Approvals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkAssign',
            fields=[
            ],
            options={
                'verbose_name': 'Bulk Assign',
                'verbose_name_plural': 'Bulk Assign Agreements',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agreement_Approvals.agreement',),
        ),
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard Stats',
                'verbose_name_plural': 'Dashboard Stats',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agreement_Approvals.agreement',),
        ),
        migrations.CreateModel(
            name='NewAgreement',
            fields=[
            ],
            options={
                'verbose_name': 'New Agreement',
                'verbose_name_plural': 'New Agreements',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agreement_Approvals.agreement',),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement_id',
            field=models.CharField(max_length=20),
        ),
    ]
