# Generated by Django 6.0.2 on 2026-02-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agreement_Approvals', '0002_bulkassign_dashboardstats_newagreement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulkAssign',
        ),
        migrations.AlterModelOptions(
            name='dashboardstats',
            options={'verbose_name': 'Dashboard Stat', 'verbose_name_plural': 'Dashboard Stats'},
        ),
        migrations.CreateModel(
            name='BulkAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.CharField(choices=[('Rahul', 'Rahul'), ('Amit', 'Amit'), ('Sneha', 'Sneha'), ('Priya', 'Priya')], max_length=50)),
                ('agreements', models.ManyToManyField(to='Agreement_Approvals.agreement')),
            ],
        ),
    ]
