# Generated by Django 4.2.7 on 2026-02-18 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_email', models.EmailField(max_length=254)),
                ('account_id', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_overdue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dpd', models.IntegerField()),
                ('bucket', models.CharField(choices=[('SMA-0', 'SMA-0'), ('SMA-1', 'SMA-1'), ('SMA-2', 'SMA-2'), ('NPA', 'NPA')], max_length=10)),
                ('customer_name', models.CharField(max_length=100)),
                ('loan_number', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RepossessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('repossessed_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('neft', 'NEFT'), ('rtgs', 'RTGS')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('cheque_number', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='recovery_receipts/')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_type', models.CharField(choices=[('field_visit', 'Field Visit'), ('phone_call', 'Phone Call'), ('promise_to_pay', 'Promise To Pay')], max_length=30)),
                ('disposition', models.CharField(choices=[('right_party', 'Right Party Contact'), ('wrong_party', 'Wrong Party Contact'), ('no_contact', 'No Contact'), ('switched_off', 'Switched Off'), ('call_back', 'Call Back Later'), ('promise_to_pay', 'Promise to Pay')], max_length=30)),
                ('contact_person', models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('family', 'Family Member'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField()),
                ('promise_date', models.DateField(blank=True, null=True)),
                ('ptp_date', models.DateField(blank=True, null=True)),
                ('ptp_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('voice_recording', models.FileField(blank=True, null=True, upload_to='voice_recordings/')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='accounts.account')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
