# Generated by Django 4.2.7 on 2026-02-10 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0004_alter_customer_kyc_status_alter_customer_tenant_and_more'),
        ('tenants', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PAN', 'PAN'), ('AADHAAR', 'Aadhaar'), ('BANK_STATEMENT', 'Bank Statement'), ('SALARY_SLIP', 'Salary Slip'), ('GST_RETURN', 'GST Return'), ('OTHERS', 'Others')], default='OTHERS', max_length=50)),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
