# Generated by Django 4.2.7 on 2026-02-12 12:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import los.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('application_number', models.CharField(default=los.models.generate_application_number, editable=False, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian mobile number', regex='^[6-9]\\d{9}$')])),
                ('email', models.EmailField(max_length=254)),
                ('pan', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter valid PAN number', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')])),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter valid 12 digit Aadhaar number', regex='^\\d{12}$')])),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('res_address_line1', models.CharField(max_length=255)),
                ('res_address_line2', models.CharField(blank=True, max_length=255)),
                ('res_city', models.CharField(max_length=100)),
                ('res_state', models.CharField(max_length=100)),
                ('res_pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter valid 6 digit pincode', regex='^\\d{6}$')])),
                ('res_country', models.CharField(default='India', max_length=100)),
                ('office_address_line1', models.CharField(blank=True, max_length=255)),
                ('office_city', models.CharField(blank=True, max_length=100)),
                ('office_pincode', models.CharField(blank=True, max_length=6)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requested_tenure', models.PositiveIntegerField(help_text='Tenure in months')),
                ('net_monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('income_type', models.CharField(choices=[('SALARIED', 'Salaried'), ('SELF_EMPLOYED', 'Self Employed')], max_length=20)),
                ('employment_type', models.CharField(choices=[('PRIVATE', 'Private'), ('GOVERNMENT', 'Government'), ('BUSINESS', 'Business'), ('OTHER', 'Other')], max_length=20)),
                ('employer_name', models.CharField(blank=True, max_length=255)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter valid IFSC code', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current')], max_length=20)),
                ('pan_card', models.FileField(upload_to='kyc/')),
                ('address_proof', models.FileField(upload_to='kyc/')),
                ('bank_statement', models.FileField(upload_to='kyc/')),
                ('salary_slip', models.FileField(blank=True, null=True, upload_to='kyc/')),
                ('self_declaration_video', models.FileField(blank=True, null=True, upload_to='kyc/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('HOUSE', 'House'), ('FLAT', 'Flat / Apartment'), ('PLOT', 'Plot / Land'), ('VILLA', 'Villa'), ('COMMERCIAL', 'Commercial Property')], max_length=30)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_detail', to='los.loanapplication')),
            ],
            options={
                'db_table': 'property_details',
            },
        ),
        migrations.CreateModel(
            name='MortgageUnderwriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_market_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ltv_on_property', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_eligible_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('approved_at', models.DateTimeField(auto_now=True)),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_underwriting', to='los.loanapplication')),
            ],
            options={
                'db_table': 'mortgage_underwriting',
            },
        ),
        migrations.CreateModel(
            name='CreditAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SYSTEM_APPROVED', 'System Approved'), ('SYSTEM_REJECTED', 'System Rejected'), ('MANUAL_APPROVED', 'Manual Approved'), ('MANUAL_REJECTED', 'Manual Rejected')], max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_assessment', to='los.loanapplication')),
            ],
            options={
                'db_table': 'credit_assessments',
            },
        ),
    ]
