# Generated by Django 4.2.10 on 2026-03-24 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyVerificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('agency_level', models.CharField(blank=True, max_length=100, null=True)),
                ('agency_type', models.CharField(max_length=255)),
                ('verification_stage', models.CharField(max_length=255)),
                ('report_type', models.CharField(max_length=255)),
                ('turnaround_time', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rm_agency_verification_rules',
            },
        ),
        migrations.CreateModel(
            name='ClientProfileRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=255)),
                ('parameter', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('impact_value', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rm_client_profile_rules',
            },
        ),
        migrations.CreateModel(
            name='CollateralQualityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collateral_type', models.CharField(max_length=100)),
                ('ownership', models.CharField(max_length=100)),
                ('min_market_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('max_market_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('allowed_ltv', models.CharField(max_length=20)),
                ('risk_level', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rm_collateral_quality_rules',
            },
        ),
        migrations.CreateModel(
            name='CreditHistoryRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_bureau', models.CharField(max_length=100)),
                ('min_credit_score', models.IntegerField(default=0)),
                ('max_dpd_days', models.IntegerField(default=0)),
                ('max_enquiries', models.IntegerField(default=0)),
                ('risk_level', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rm_credit_history_rules',
            },
        ),
        migrations.CreateModel(
            name='FinancialEligibilityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('income_type', models.CharField(max_length=100)),
                ('min_monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('min_business_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('min_annual_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('min_bank_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_flow_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('max_emi_ratio', models.CharField(max_length=20)),
                ('itr_required', models.BooleanField(default=False)),
                ('cash_flow_check', models.BooleanField(default=False)),
                ('compliance_check', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rm_financial_eligibility_rules',
            },
        ),
        migrations.CreateModel(
            name='GeoLocationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('risk_level', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rm_geo_location_rules',
            },
        ),
        migrations.CreateModel(
            name='ImpactValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rm_impact_values',
            },
        ),
        migrations.CreateModel(
            name='InternalScoreRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameter', models.CharField(max_length=100)),
                ('min_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('risk_level', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rm_internal_score_rules',
            },
        ),
        migrations.CreateModel(
            name='InternalVerificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(max_length=255)),
                ('criteria', models.TextField()),
                ('turnaround_days', models.IntegerField(default=0)),
                ('flag_mismatch', models.BooleanField(default=False)),
                ('flag_duplicate_pan', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rm_internal_verification_rules',
            },
        ),
        migrations.CreateModel(
            name='RiskMitigationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_parameter', models.CharField(max_length=255)),
                ('mitigation_action', models.TextField()),
                ('severity', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rm_risk_mitigation_rules',
            },
        ),
        migrations.CreateModel(
            name='RuleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255)),
                ('rule_code', models.CharField(choices=[('CLIENT_PROFILE', 'Client Profile Engine'), ('COLLATERAL', 'Collateral Quality Engine'), ('FINANCIAL', 'Financial Eligibility Engine'), ('SCORECARD', 'Score Card Engine'), ('VERIFICATION', 'Verification Engine'), ('RISK', 'Risk & Mitigation Engine')], max_length=50)),
                ('rule_type', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('segment', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rm_rule_master',
            },
        ),
        migrations.CreateModel(
            name='TenantRuleConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rulemanagement_tenant_rules',
            },
        ),
    ]
