# Generated by Django 4.2.7 on 2025-11-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_branch_options_tenant_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='updated_at',
        ),
    ]
