# Generated by Django 4.2.7 on 2025-12-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_client_delete_clientonboarding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='kyc_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
        migrations.AddField(
            model_name='client',
            name='kyc_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
    ]
