# Generated by Django 4.2.7 on 2025-12-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_rename_phone_client_mobile_remove_client_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='city',
        ),
    ]
