# Generated by Django 4.2.7 on 2025-12-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_remove_branch_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='email',
        ),
    ]
