# Generated by Django 4.2.7 on 2025-12-11 10:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_workinghours_workingday_reportingperiod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Calendar', max_length=100)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='tenants.tenant')),
            ],
            options={
                'db_table': 'calendar_master',
            },
        ),
        migrations.RemoveField(
            model_name='workingday',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='OvertimeSettings',
        ),
        migrations.DeleteModel(
            name='WorkingDay',
        ),
        migrations.DeleteModel(
            name='WorkingHours',
        ),
       migrations.AddField(
    model_name='financialyear',
    name='calendar',
    field=models.ForeignKey(null=True,blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_years', to='tenants.calendar'),
    preserve_default=False,
),
migrations.AddField(
    model_name='holiday',
    name='calendar',
    field=models.ForeignKey(null=True,blank=True,on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='tenants.calendar'),
    preserve_default=False,
),
migrations.AddField(
    model_name='reportingperiod',
    name='calendar',
    field=models.ForeignKey(null=True,blank=True ,on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='tenants.calendar'),
    preserve_default=False,
),
    ]
