# Generated by Django 4.2.7 on 2025-12-11 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_calendar_remove_workingday_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_years', to='tenants.calendar'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='tenants.calendar'),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='tenants.calendar'),
        ),
        migrations.CreateModel(
            name='TenantRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule_config', to='tenants.tenant')),
            ],
        ),
    ]
