# Generated by Django 4.2.7 on 2025-12-12 10:24

from django.db import migrations, models
import django.db.models.deletion


def safe_delete_calendar_table(apps, schema_editor):
    """
    Safely drop the old calendar table if it exists.
    This prevents SQLite 'no such table' errors.
    """
    try:
        schema_editor.execute("DROP TABLE IF EXISTS calendar_master;")
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_alter_financialyear_calendar_alter_holiday_calendar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_key', models.CharField(choices=[('loan', 'Loan Category'), ('product', 'Product Category'), ('document', 'Document Category'), ('lead', 'Lead Category'), ('source', 'Source Category'), ('customer', 'Customer Category'), ('internal_team', 'Internal Team Category'), ('external_team', 'External Team Category')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenants.tenant')),
            ],
            options={
                'db_table': 'categories',
                'ordering': ('category_key', 'title'),
            },
        ),
        migrations.RemoveField(
            model_name='financialyear',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='reportingperiod',
            name='calendar',
        ),
        
        # ❌ REMOVE DeleteModel because it fails on SQLite
        # migrations.DeleteModel(name='Calendar'),

        # ✅ REPLACE WITH SAFE TABLE DROP
        migrations.RunPython(safe_delete_calendar_table, reverse_code=migrations.RunPython.noop),
    ]
