# Generated by Django 4.2.7 on 2025-12-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_category_remove_financialyear_calendar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
