# Generated by Django 4.2.7 on 2025-12-12 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_subscription_status'),
        ('tenants', '0013_delete_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='adminpanel.subscription'),
        ),
    ]
