# Generated by Django 4.2.10 on 2026-03-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScoreRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('SALARIED', 'Salaried'), ('BUSINESS', 'BUSINESS')], max_length=20)),
                ('parameter', models.CharField(choices=[('CIBIL', 'CIBIL Score'), ('SALARY', 'Salary'), ('AGE', 'Age'), ('FOIR', 'FOIR')], max_length=20)),
                ('condition', models.CharField(choices=[('GT', 'Greater Than'), ('LT', 'Less Than'), ('BT', 'Between')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impact_score', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'risk_credit_score_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NegativeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High (Manual Review)'), ('BLOCKED', 'Blocked')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'risk_negative_areas',
            },
        ),
    ]
