# Generated by Django 6.0.2 on 2026-02-24 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Document', 'Document'), ('KYC', 'KYC'), ('Disbursement', 'Disbursement'), ('Portal Access', 'Portal Access'), ('Others', 'Others')], max_length=50)),
                ('sub_category', models.CharField(choices=[('Login Issue', 'Login Issue'), ('Bug', 'Bug'), ('Performance', 'Performance'), ('Upload Failed', 'Upload Failed'), ('Incorrect Document', 'Incorrect Document'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Mismatch', 'Mismatch'), ('Delay', 'Delay'), ('Amount Mismatch', 'Amount Mismatch'), ('Access Denied', 'Access Denied'), ('Role Issue', 'Role Issue'), ('General', 'General')], max_length=50)),
                ('ticket_type', models.CharField(choices=[('Complaint', 'Complaint'), ('Request', 'Request'), ('Query', 'Query')], max_length=20)),
                ('assigned_to', models.CharField(choices=[('Support Team', 'Support Team'), ('IT Support', 'IT Support'), ('Ops Team', 'Ops Team')], max_length=50)),
                ('status', models.CharField(choices=[('IN_progress', 'in_progress'), ('open', 'open'), ('escalated', 'escalated')], max_length=50)),
                ('customer_id', models.CharField(max_length=255)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('channel_name', models.CharField(max_length=100, unique=True)),
                ('channel_type', models.CharField(choices=[('social', 'Social'), ('aggregator', 'Aggregator'), ('offline', 'Offline'), ('referral', 'Referral'), ('internal', 'Internal'), ('messaging', 'Messaging'), ('email', 'Email Campaign'), ('telecalling', 'Telecalling')], max_length=20)),
                ('source_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('integration_required', models.BooleanField(default=False)),
                ('api_url', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('Origin_type', models.CharField(choices=[('aggregator', 'Aggregator'), ('social media', 'Social Media'), ('offline/referal', 'Offline/Referal')], max_length=20)),
                ('Operational_valve', models.CharField(choices=[('telecaller', 'Telecaller'), ('field agent', 'Field Agent')], max_length=20)),
                ('cost_per_lead', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('default_team', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_leads', models.IntegerField(default=0)),
                ('total_conversions', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_response_time', models.FloatField(default=0)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Support_And_Operations.channel')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Support_And_Operations.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=20)),
                ('mode', models.CharField(choices=[('chat', 'Chat'), ('email', 'Email'), ('call', 'Call'), ('whatsapp', 'WhatsApp'), ('meet', 'Meet'), ('slack', 'Slack')], max_length=20)),
                ('lead_id', models.CharField(blank=True, max_length=50, null=True)),
                ('deal_id', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message_content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read'), ('not_read', 'Not Read'), ('replied', 'Replied')], default='sent', max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='outbound', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='communication_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Support_And_Operations.communication')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('training_format', models.CharField(choices=[('Video', 'Video'), ('Document', 'Document'), ('Live Session', 'Live Session'), ('Quiz', 'Quiz')], max_length=20)),
                ('trainer_name', models.CharField(max_length=255)),
                ('training_material', models.FileField(blank=True, null=True, upload_to='training_materials/')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('completion_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('feedback_rating', models.IntegerField(blank=True, null=True)),
                ('assessment_required', models.BooleanField(default=False)),
                ('quiz_file', models.FileField(blank=True, null=True, upload_to='quiz_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_trainings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
