# Generated by Django 4.2.7 on 2026-03-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Support_And_Operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='category',
            field=models.CharField(blank=True, choices=[('Onboarding', 'Onboarding'), ('Product Knowledge', 'Product Knowledge'), ('Soft Skills', 'Soft Skills'), ('Process', 'Process')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='progress',
            field=models.IntegerField(default=0, help_text='Completion percentage'),
        ),
        migrations.AddField(
            model_name='training',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='training_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
