# Generated by Django 5.2.11 on 2026-02-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('AML_MATCH', 'AML Match'), ('HIGH_FRAUD', 'High Fraud Score'), ('DOC_MISMATCH', 'Document Mismatch')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('fraud_score', models.IntegerField()),
                ('aml_status', models.CharField(choices=[('HIT', 'HIT'), ('CLEAR', 'CLEAR')], max_length=10)),
                ('status', models.CharField(choices=[('REVIEW', 'REVIEW'), ('PENDING', 'PENDING'), ('APPROVED', 'APPROVED')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('fraud_probability', models.FloatField()),
                ('is_synthetic_id', models.BooleanField(default=False)),
                ('is_aml_hit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_score', models.IntegerField(default=0)),
                ('synthetic_id_alerts', models.IntegerField(default=0)),
                ('aml_hits', models.IntegerField(default=0)),
                ('behavioral_flags', models.IntegerField(default=0)),
                ('pattern_matches', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
