# Generated by Django 5.2.12 on 2026-03-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('field_agent', 'Field Verification Agent'), ('collection_agent', 'Collection Agent'), ('channel_partner', 'Channel Partner'), ('admin', 'Admin'), ('collection agent', 'Collection Agent (Legacy)'), ('channel partener', 'Channel Partner (Legacy)')], default='field_agent', max_length=30),
        ),
    ]
