# Generated by Django 6.0.2 on 2026-02-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenantuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantuser',
            name='tenant_id',
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
