# Generated by Django 6.0.2 on 2026-02-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenantuser', '0002_remove_tenantuser_tenant_id_alter_tenantuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='action',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='TAKEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='role_type',
            field=models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('STAFF', 'Staff Member'), ('ADMIN', 'Tenant Admin'), ('LOAN', 'Loan Officer'), ('COLLECTION', 'Collection Agent')], max_length=20),
        ),
    ]
