# Generated by Django 4.2.7 on 2026-02-16 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0005_rename_status_role_role_status'),
        ('tenantuser', '0003_tenantuser_action_alter_tenantuser_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.role'),
        ),
    ]
