# Generated by Django 5.2.11 on 2026-03-03 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('agent_type', models.CharField(choices=[('DSA', 'DSA'), ('BROKER', 'Broker'), ('LEAD_PARTNER', 'Lead Partner')], max_length=20)),
                ('review_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half Yearly'), ('ANNUAL', 'Annual')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft')], default='DRAFT', max_length=10)),
                ('bronze_min', models.IntegerField(default=0)),
                ('bronze_max', models.IntegerField(default=49)),
                ('bronze_bonus', models.IntegerField(default=0)),
                ('silver_min', models.IntegerField(default=50)),
                ('silver_max', models.IntegerField(default=74)),
                ('silver_bonus', models.IntegerField(default=2000)),
                ('gold_min', models.IntegerField(default=75)),
                ('gold_max', models.IntegerField(default=89)),
                ('gold_bonus', models.IntegerField(default=5000)),
                ('platinum_min', models.IntegerField(default=90)),
                ('platinum_max', models.IntegerField(default=100)),
                ('platinum_bonus', models.IntegerField(default=10000)),
                ('cancel', models.BooleanField(default=False)),
                ('create_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('target', models.IntegerField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='performance_template.newtemplate')),
            ],
        ),
    ]
