# Generated by Django 5.2.11 on 2026-03-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_template', '0002_newtemplate_performancemetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetric',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
