# Generated by Django 6.0.2 on 2026-02-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('RTGS', 'RTGS'), ('NEFT', 'NEFT')], max_length=20),
        ),
    ]
