# Generated by Django 6.0.2 on 2026-02-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_dashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
