# Generated by Django 6.0.2 on 2026-02-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_delete_dashboard_alter_disbursement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_disbursement', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collection_rate', models.FloatField(default=0)),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
