# Generated by Django 6.0.2 on 2026-03-01 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_quickaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickAction',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='loan_id',
        ),
        migrations.AddField(
            model_name='repayment',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.loan'),
        ),
    ]
