# Generated by Django 5.2.11 on 2026-02-17 12:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgotpassword', '0002_passwordresettoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordResetRequest',
            new_name='ForgotPasswordOTP',
        ),
        migrations.RenameModel(
            old_name='PasswordResetToken',
            new_name='ResetPasswordToken',
        ),
    ]
