# Generated by Django 5.2.11 on 2026-02-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgotpassword', '0003_rename_passwordresetrequest_forgotpasswordotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpasswordtoken',
            name='confirm_new_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='resetpasswordtoken',
            name='new_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
