# Generated by Django 5.2.11 on 2026-02-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgotpassword', '0004_resetpasswordtoken_confirm_new_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpasswordtoken',
            name='token',
        ),
    ]
