# Generated by Django 5.2.11 on 2026-02-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgotpassword', '0005_remove_resetpasswordtoken_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpasswordtoken',
            name='created_at',
        ),
    ]
