# Generated by Django 4.2.7 on 2026-01-13 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScoreRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('CIBIL Score', 'CIBIL Score'), ('SALARY', 'SALARY'), ('Age', 'Age'), ('FOIR', 'FOIR')], max_length=20)),
                ('parameter', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('GT', 'Greater Than'), ('LT', 'Less Than'), ('BT', 'Between')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impact_score', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_rules', to='tenants.tenant')),
            ],
            options={
                'db_table': 'risk_credit_score_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NegativeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High (Manual Review)'), ('BLOCKED', 'Blocked')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negative_areas', to='tenants.tenant')),
            ],
            options={
                'db_table': 'risk_negative_areas',
                'unique_together': {('tenant', 'pincode')},
            },
        ),
    ]
