# Generated by Django 4.2.7 on 2026-01-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='negativearea',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='creditscorerule',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='creditscorerule',
            name='employment_type',
            field=models.CharField(choices=[('SALARIED', 'Salaried'), ('SELF_EMPLOYED', 'Self Employed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='creditscorerule',
            name='parameter',
            field=models.CharField(choices=[('CIBIL', 'CIBIL Score'), ('SALARY', 'Salary'), ('AGE', 'Age'), ('FOIR', 'FOIR')], max_length=20),
        ),
        migrations.AlterField(
            model_name='negativearea',
            name='pincode',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.RemoveField(
            model_name='negativearea',
            name='tenant',
        ),
    ]
