# Generated by Django 4.2.7 on 2026-01-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_engine', '0002_alter_negativearea_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditscorerule',
            name='employment_type',
            field=models.CharField(choices=[('SALARIED', 'Salaried'), ('BUSINESS', 'BUSINESS')], max_length=20),
        ),
    ]
