# Generated by Django 5.2.11 on 2026-02-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Land', 'Land')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(choices=[('Vikram Mehta', 'Vikram Mehta'), ('Priya Sharma', 'Priya Sharma'), ('Rajesh Kumar', 'Rajesh Kumar')], max_length=100)),
                ('select_agent', models.CharField(max_length=255)),
                ('action_status', models.CharField(choices=[('Cancel', 'Cancel')], default='Cancel', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
