# Generated by Django 5.2.11 on 2026-02-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycheck',
            name='action_status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Create check', 'Create Check')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propertycheck',
            name='property_type',
            field=models.CharField(max_length=50),
        ),
    ]
