# Generated by Django 5.2.11 on 2026-02-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_check', '0002_alter_propertycheck_action_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertycheck',
            name='select_agent',
        ),
    ]
