# Generated by Django 5.2.11 on 2026-02-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_check', '0003_remove_propertycheck_select_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_properties', models.IntegerField(default=0)),
                ('pending_checks', models.IntegerField(default=0)),
                ('in_progress', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
