# Generated by Django 5.2.11 on 2026-02-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_check', '0004_propertydashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydashboard',
            name='created_at',
        ),
        migrations.AddField(
            model_name='propertydashboard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='propertydashboard',
            name='completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertydashboard',
            name='in_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertydashboard',
            name='pending_checks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertydashboard',
            name='total_properties',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
