# Generated by Django 6.0.2 on 2026-03-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_check', '0005_remove_propertydashboard_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertycheck',
            name='action_status',
        ),
    ]
