# Generated by Django 6.0.2 on 2026-02-26 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingtask',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pendingtask',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='pendingtask',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='pendingtask',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('INCOMPLETE', 'INCOMPLETE')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
