# Generated by Django 6.0.2 on 2026-02-26 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_pendingtask_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtask',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
