# Generated by Django 6.0.2 on 2026-02-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_pendingtask_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingtask',
            old_name='status',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='pendingtask',
            old_name='task_type',
            new_name='type',
        ),
    ]
