# Generated by Django 6.0.2 on 2026-02-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_status_pendingtask_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtask',
            name='action',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('INPROGRESS', 'inprogress'), ('REJECTED', 'REJECTED')], max_length=20),
        ),
    ]
