# Generated by Django 6.0.2 on 2026-03-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_pendingtask_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLABreachAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium')], default='MEDIUM', max_length=10)),
                ('sla_hours', models.IntegerField(help_text='Allowed SLA time in hours')),
                ('elapsed_hours', models.IntegerField(help_text='Time already spent in hours')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('is_escalated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
