# Generated by Django 4.2.7 on 2026-02-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualifiedLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('ALL', 'All'), ('ELIGIBLE', 'Eligible'), ('DOCUMENTS_PENDING', 'Documents Pending'), ('UNDER_REVIEW', 'Under Review'), ('INELIGIBLE', 'Ineligible')], default='UNDER_REVIEW', max_length=20)),
                ('interest', models.CharField(choices=[('home_loan', 'Home Loan'), ('personal_loan', 'Personal Loan'), ('car_loan', 'Car Loan'), ('credit_card', 'Credit Card'), ('business_loan', 'Business Loan'), ('education_loan', 'Education Loan'), ('other', 'Other Services')], default='home_loan', max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('next_action', models.CharField(blank=True, choices=[('call', 'Schedule Call'), ('meeting', 'Schedule Meeting'), ('follow_up', 'Follow-up'), ('document_collection', 'Collect Documents'), ('eligibility_check', 'Run Eligibility Check')], max_length=50, null=True)),
                ('qualification_notes', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline_lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='pipeline.pipelinelead')),
            ],
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_score', models.IntegerField(default=0)),
                ('income_score', models.IntegerField(default=0)),
                ('credit_score', models.IntegerField(default=0)),
                ('property_score', models.IntegerField(default=0)),
                ('overall_percentage', models.IntegerField(default=0)),
                ('status', models.CharField(default='Under Review', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='qualified_leads.qualifiedlead')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('salary_slips', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('employment_proof', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='qualified_leads.qualifiedlead')),
            ],
        ),
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('hot', 'Hot Lead'), ('ineligible', 'Ineligible')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interest_area', models.CharField(blank=True, choices=[('select', 'Select Interest Area / Product'), ('home_loan', 'Home Loan'), ('personal_loan', 'Personal Loan'), ('car_loan', 'Car Loan'), ('credit_card', 'Credit Card'), ('business_loan', 'Business Loan'), ('education_loan', 'Education Loan'), ('other_services', 'Other Services')], max_length=50, null=True)),
                ('expected_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, choices=[('select', 'Select Next Action'), ('schedule_meeting', 'Schedule Meeting'), ('schedule_call', 'Schedule Call'), ('follow_up', 'Follow Up'), ('documents', 'Collect Documents'), ('run_eligibility_check', 'Run Eligibility Check')], max_length=50, null=True)),
                ('qualification_notes', models.TextField(blank=True, null=True)),
                ('qualified_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='qualified_leads.qualifiedlead')),
            ],
        ),
    ]
