# Generated by Django 4.2.7 on 2026-02-04 09:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0004_rename_name_business_business_name_and_more'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=150)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian mobile number', regex='^[6-9]\\d{9}$')])),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('branch_password', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_products', models.ManyToManyField(blank=True, related_name='branches', to='product.product')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='businesses.business')),
            ],
            options={
                'db_table': 'tenant_branches',
                'ordering': ['-created_at'],
                'unique_together': {('business', 'email')},
            },
        ),
    ]
