# Generated by Django 4.2.7 on 2026-02-27 13:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bulk_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIngestionDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_raw_pool', models.IntegerField(default=0)),
                ('validation_pass', models.FloatField(default=0.0)),
                ('pending_assignment', models.IntegerField(default=0)),
                ('suppressed_leads', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SuppressionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('suppression_reason', models.CharField(choices=[('consent_no', 'Consent Marked No.'), ('regulatory_block', 'Regulatory Block'), ('manual_suppression', 'Manual Suppression')], max_length=50)),
                ('blocked_date', models.DateField()),
                ('action_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationEngineConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.BooleanField(default=True, help_text='Reject leads missing a name')),
                ('phone_number', models.BooleanField(default=True, help_text='Primary contact verification')),
                ('email_address', models.BooleanField(default=True, help_text='Electronic contact verification')),
                ('mobile_dedupe', models.BooleanField(default=True, help_text='Check for existing phone numbers')),
                ('email_dedupe', models.BooleanField(default=True, help_text='Check for existing email addresses')),
                ('rejection_note', models.TextField(blank=True, help_text='Leads failing these checks will move to Rejected Pool', null=True)),
                ('clean_raw_pool', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.CharField(choices=[('raw', 'Raw Pool'), ('rejected', 'Rejected Pool'), ('stage_2', 'Stage 2')], default='raw', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RawLeadPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('source', models.CharField(choices=[('csv', 'CSV Upload'), ('api_justdial', 'API - JustDial'), ('manual', 'Manual Entry'), ('fb_campaign', 'FB Campaign')], max_length=50)),
                ('validation_status', models.CharField(choices=[('verified', 'Verified'), ('duplicate', 'Duplicate'), ('incomplete', 'Incomplete')], default='incomplete', max_length=50)),
                ('ingested_at', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.CharField(blank=True, choices=[('agent_a', 'Agent A (Capacity: 120)'), ('agent_b', 'Agent B (Capacity: 120)'), ('agent_c', 'Agent C (Capacity: 120)')], max_length=20, null=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_lead_pool', to='bulk_upload.manualentry')),
            ],
        ),
    ]
