# Generated by Django 4.2.7 on 2026-02-24 14:48
# NOTE: Operations removed – 0001_initial already creates RawLeadPool and
# the stage field on ValidationEngineConfiguration.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
    ]
