# Generated by Django 4.2.7 on 2026-03-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_upload', '0001_initial'),
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawleadpool',
            name='lead',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='bulk_upload.manualentry'),
            preserve_default=False,
        ),
    ]
