# Generated by Django 4.2.7 on 2026-03-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_upload', '0001_initial'),
        ('data_ingestion', '0002_rawleadpool_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawleadpool',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_lead_pool', to='bulk_upload.manualentry'),
        ),
    ]
