# Generated by Django 4.2.7 on 2026-03-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0002_rename_rawlead_rawleadpool_and_more'),
        ('data_ingestion', '0003_alter_rawleadpool_lead'),
    ]

    operations = [
    ]
