# Generated by Django 4.2.7 on 2026-03-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0004_merge_20260310_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawleadpool',
            name='lead',
        ),
    ]
