# Generated by Django 5.2.11 on 2026-03-05 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remaining_principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate %', max_digits=5)),
                ('tenure_months', models.PositiveIntegerField()),
                ('monthly_emi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disbursed_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_component', models.DecimalField(decimal_places=2, help_text='Part of EMI reducing principal', max_digits=12)),
                ('interest_component', models.DecimalField(decimal_places=2, help_text='Part of EMI paying interest', max_digits=12)),
                ('due_date', models.DateField()),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('partially_paid', 'Partially Paid')], default='scheduled', max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emis', to='loan.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('education', 'Education Loan'), ('consumer', 'Consumer Durable Loan'), ('gold', 'Gold Loan'), ('property', 'Loan Against Property'), ('vehicle', 'Vehicle Loan'), ('securities', 'Loan Against Securities'), ('supply_chain', 'Supply Chain Financing')], max_length=50)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('document_required', 'Document Required'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=30)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('loan_purpose', models.TextField()),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='loan_docs/pan/')),
                ('aadhar_front', models.FileField(blank=True, null=True, upload_to='loan_docs/aadhar/front/')),
                ('aadhar_back', models.FileField(blank=True, null=True, upload_to='loan_docs/aadhar/back/')),
                ('income_proof', models.FileField(blank=True, null=True, upload_to='loan_docs/income/')),
                ('itr_last_year', models.FileField(blank=True, null=True, upload_to='loan_docs/itr/')),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to='loan_docs/bank_statements/')),
                ('employment_proof', models.FileField(blank=True, null=True, upload_to='loan_docs/employment_proof/')),
                ('salary_slip', models.FileField(blank=True, null=True, upload_to='loan_docs/salary_slip/')),
                ('business_registration_documents', models.FileField(blank=True, null=True, upload_to='loan_docs/business_registration/')),
                ('gst_returns', models.FileField(blank=True, null=True, upload_to='loan_docs/gst_returns/')),
                ('financial_statements', models.FileField(blank=True, null=True, upload_to='loan_docs/financial_statements/')),
                ('admission_letter', models.FileField(blank=True, null=True, upload_to='loan_docs/admission_letter/')),
                ('fee_structure', models.FileField(blank=True, null=True, upload_to='loan_docs/fee_structure/')),
                ('academic_records', models.FileField(blank=True, null=True, upload_to='loan_docs/academic_records/')),
                ('collateral_documents', models.FileField(blank=True, null=True, upload_to='loan_docs/collateral_documents/')),
                ('invoice_product', models.FileField(blank=True, null=True, upload_to='loan_docs/product_invoice/')),
                ('gold_ornaments', models.FileField(blank=True, null=True, upload_to='loan_docs/gold_ornaments/')),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='loan_docs/address_proof/')),
                ('property_papers', models.FileField(blank=True, null=True, upload_to='loan_docs/property_papers/')),
                ('title_deed', models.FileField(blank=True, null=True, upload_to='loan_docs/title_deed/')),
                ('valuation_report', models.FileField(blank=True, null=True, upload_to='loan_docs/valuation_report/')),
                ('driving_license', models.FileField(blank=True, null=True, upload_to='loan_docs/driving_license/')),
                ('vehicle_quotation', models.FileField(blank=True, null=True, upload_to='loan_docs/vehicle_quotation/')),
                ('demat_account_statements', models.FileField(blank=True, null=True, upload_to='loan_docs/demat_statements/')),
                ('securities_pledge_agreement', models.FileField(blank=True, null=True, upload_to='loan_docs/pledge_agreement/')),
                ('invoices', models.FileField(blank=True, null=True, upload_to='loan_docs/invoices/')),
                ('buyer_supplier_agreements', models.FileField(blank=True, null=True, upload_to='loan_docs/agreements/')),
                ('business_financials', models.FileField(blank=True, null=True, upload_to='loan_docs/business_financials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='loan.loanapplication'),
        ),
    ]
