# Generated by Django 5.2.11 on 2026-03-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='application_id',
            field=models.CharField(default='LA2024001234', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
