# Generated by Django 5.2.11 on 2026-03-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loanapplication_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='current_stage',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('document_required', 'Document Required'), ('sanction_process', 'Sanction Process'), ('kfs_review', 'KFS Review'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('rejected', 'Rejected')], default='submitted', max_length=30),
        ),
    ]
