# Generated by Django 5.2.11 on 2026-03-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loan_current_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='remaining_balance_after_emi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='current_stage',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('sanction_process', 'Sanction Process'), ('kfs_review', 'KFS Review'), ('disbursed', 'Disbursed')], default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
