# Generated by Django 5.2.11 on 2026-03-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_emi_remaining_balance_after_emi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='emi_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
