# Generated by Django 5.2.11 on 2026-03-09 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_emi_emi_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyFactStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_percentage_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_amount_payable', models.DecimalField(decimal_places=2, max_digits=14)),
                ('late_payment_charges', models.CharField(max_length=200)),
                ('prepayment_charges', models.CharField(max_length=200)),
                ('bounce_charges', models.CharField(max_length=200)),
                ('legal_charges', models.CharField(max_length=200)),
                ('generated_on', models.DateField(auto_now_add=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kfs', to='loan.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(max_length=30, unique=True)),
                ('agreement_date', models.DateField()),
                ('agreement_file', models.FileField(blank=True, null=True, upload_to='loan_docs/agreements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='loan.loan')),
            ],
        ),
        migrations.CreateModel(
            name='SanctionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_number', models.CharField(max_length=30, unique=True)),
                ('sanction_date', models.DateField()),
                ('valid_till', models.DateField()),
                ('processing_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sanction_letter', to='loan.loan')),
            ],
        ),
        migrations.CreateModel(
            name='SanctionTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sanction_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='loan.sanctionletter')),
            ],
        ),
    ]
