# Generated by Django 5.2.12 on 2026-03-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_keyfactstatement_loanagreement_sanctionletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='current_stage',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('sanction_process', 'Sanction Process'), ('kfs_review', 'KFS Review'), ('kfs_completed', 'KFS Completed'), ('disbursed', 'Disbursed')], default='submitted', max_length=30),
        ),
    ]
