# Generated by Django 4.2.7 on 2026-01-02 17:25

from django.db import migrations, models
import django.db.models.deletion
import tenants.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('FEE', 'Fee'), ('PENALTY', 'Penalty')], default='FEE', max_length=20)),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One-time'), ('RECURRING', 'Recurring')], default='ONE_TIME', max_length=20)),
                ('basis', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage'), ('SLAB', 'Slab Based')], default='FIXED', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='Value or %', max_digits=10)),
                ('slab_config', models.JSONField(blank=True, default=dict, help_text="{'1-30 days': 2%, '31-60 days': 4%}")),
                ('recovery_stage', models.CharField(choices=[('DISBURSEMENT', 'Deduct from Disbursement'), ('ONGOING', 'Ongoing'), ('MISSED_EMI', 'Missed EMI'), ('POST_DEFAULT', 'Post Default')], default='DISBURSEMENT', max_length=50)),
                ('recovery_mode', models.CharField(choices=[('AUTO', 'Auto (Next Bill)'), ('MANUAL', 'Manual Collection')], default='AUTO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenant_charge_configs',
            },
        ),
        migrations.CreateModel(
            name='InterestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('interest_type', models.CharField(choices=[('FIXED', 'Fixed Rate'), ('FLOATING', 'Floating Rate')], default='FIXED', max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Annual Rate %', max_digits=5)),
                ('benchmark_type', models.CharField(blank=True, choices=[('REPO', 'RBI Repo Rate'), ('MCLR', 'Bank MCLR'), ('TBILL', 'T-Bill Rate')], max_length=20, null=True)),
                ('spread_margin', models.DecimalField(decimal_places=2, default=0.0, help_text='Mark Up', max_digits=5)),
                ('accrual_method', models.CharField(choices=[('SIMPLE', 'Simple'), ('COMPOUND', 'Compound')], default='SIMPLE', max_length=20)),
                ('accrual_stage', models.CharField(choices=[('PRE_EMI', 'Pre-EMI'), ('POST_EMI', 'Post-EMI')], default='POST_EMI', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenant_interest_configs',
            },
        ),
        migrations.CreateModel(
            name='RepaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('schedule_type', models.CharField(choices=[('EMI', 'EMI'), ('BULLET', 'Bullet'), ('STEP_UP', 'Step-up')], default='EMI', max_length=50)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('BI_WEEKLY', 'Bi-weekly'), ('WEEKLY', 'Weekly')], default='MONTHLY', max_length=50)),
                ('cycle_date', models.IntegerField(default=5, help_text='Day of month (e.g., 5th)')),
                ('waterfall_sequence', models.JSONField(default=tenants.models.default_waterfall, help_text='Order of appropriation')),
                ('grace_days', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenant_repayment_configs',
            },
        ),
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('min_age', models.IntegerField(default=21)),
                ('max_age', models.IntegerField(default=60)),
                ('allowed_income_types', models.JSONField(default=list, help_text="['Salaried', 'Self-Employed']")),
                ('min_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_foir', models.DecimalField(decimal_places=2, default=60.0, help_text='Max FOIR %', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenant_risk_rules',
            },
        ),
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('SALARIED', 'Employees'), ('PROFESSIONAL', 'Professionals'), ('BUSINESS', 'Business')], default='SALARIED', max_length=50)),
                ('rules_config', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenant_scorecards',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('tenant_type', models.CharField(choices=[('BANK', 'Bank'), ('NBFC', 'NBFC'), ('P2P', 'P2P'), ('FINTECH', 'FinTech')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='adminpanel.subscription')),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule_config', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantLoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('loan_type', models.CharField(choices=[('Payday Loan (Short-term Loan)', 'Payday Loan (Short-term Loan)'), ('Personal Loan (Unsecured)', 'Personal Loan (Unsecured)'), ('Business Loan', 'Business Loan'), ('Group Loan (JLG/SHG Model)', 'Group Loan (JLG/SHG Model)'), ('Unsecured Education Loan', 'Unsecured Education Loan'), ('Consumer Durable Loan', 'Consumer Durable Loan'), ('Loan Against Property (LAP)', 'Loan Against Property (LAP)'), ('Loan Against Shares/Securities', 'Loan Against Shares/Securities'), ('Gold Loan', 'Gold Loan'), ('Vehicle Loan', 'Vehicle Loan'), ('Secured Education Loan', 'Secured Education Loan'), ('Supply Chain Finance', 'Supply Chain Finance'), ('Bill/Invoice Discounting', 'Bill/Invoice Discounting'), ('Virtual Card (Buy Now, Pay Later)', 'Virtual Card (Buy Now, Pay Later)'), ('Credit Line - OD Facility', 'Credit Line - OD Facility'), ('Agriculture Loan', 'Agriculture Loan'), ('Microfinance Loan', 'Microfinance Loan'), ('Equipment Financing', 'Equipment Financing'), ('Working Capital Loan', 'Working Capital Loan'), ('Medical Emergency Loan', 'Medical Emergency Loan')], max_length=100)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_tenure', models.IntegerField()),
                ('max_tenure', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charges', models.ManyToManyField(blank=True, to='tenants.chargeconfig')),
                ('interest_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.interestconfig')),
                ('repayment_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.repaymentconfig')),
                ('risk_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.riskrule')),
                ('scorecard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.scorecard')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_products', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_loan_products',
            },
        ),
        migrations.AddField(
            model_name='scorecard',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_rules', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='tenants.tenant')),
            ],
            options={
                'db_table': 'calendar_reporting_periods',
            },
        ),
        migrations.AddField(
            model_name='repaymentconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_configs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='interestconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_configs', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='tenants.tenant')),
            ],
            options={
                'db_table': 'calendar_holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_years', to='tenants.tenant')),
            ],
            options={
                'db_table': 'calendar_financial_years',
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('kyc_status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.AddField(
            model_name='chargeconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_configs', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_key', models.CharField(choices=[('loan', 'Loan Category'), ('product', 'Product Category'), ('document', 'Document Category'), ('lead', 'Lead Category'), ('source', 'Source Category'), ('customer', 'Customer Category'), ('internal_team', 'Internal Team Category'), ('external_team', 'External Team Category')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenants.tenant')),
            ],
            options={
                'db_table': 'categories',
                'ordering': ('category_key', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'db_table': 'branches',
            },
        ),
    ]
