# Generated by Django 6.0.1 on 2026-01-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
