# Generated by Django 4.2.7 on 2026-02-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='cin',
            field=models.CharField(blank=True, max_length=21, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='users_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
