# Generated by Django 4.2.7 on 2026-02-09 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_cin_tenant_country_tenant_gstin_tenant_pan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='subscription',
        ),
    ]
