# Generated by Django 4.2.7 on 2026-02-10 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_remove_tenant_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialyear',
            options={'ordering': ['-start'], 'verbose_name': 'Financial Year', 'verbose_name_plural': 'Financial Years'},
        ),
        migrations.RemoveField(
            model_name='financialyear',
            name='tenant',
        ),
        migrations.AddField(
            model_name='financialyear',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='financialyear',
            table=None,
        ),
    ]
