# Generated by Django 6.0.1 on 2026-01-29 15:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('registration_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', message='Enter a valid mobile number.')])),
                ('contact_person', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('Private Limited', 'Private Limited'), ('LLP', 'LLP'), ('Proprietorship', 'Proprietorship')], max_length=50)),
                ('business_pan', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{5}\\d{4}[A-Z]$', message='Enter a valid PAN.')])),
                ('owner_pan', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{5}\\d{4}[A-Z]$', message='Enter a valid PAN.')])),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1}$', message='Enter a valid GSTIN.')])),
                ('duns_number', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', message='Enter a valid DUNS number.')])),
                ('cin', models.CharField(blank=True, max_length=21, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{1}\\d{5}[A-Z]{2}\\d{4}[A-Z]{3}\\d{6}$', message='Enter a valid CIN.')])),
                ('business_website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('business_description', models.TextField()),
                ('subscription_type', models.CharField(choices=[('Trial', 'Trial'), ('Paid', 'Paid')], max_length=10)),
                ('loan_product', models.JSONField(default=list)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
