# Generated by Django 6.0.2 on 2026-02-26 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_pendingtask_action'),
        ('sitevisit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitreport',
            name='action',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.pendingtask'),
        ),
    ]
