# Generated by Django 6.0.2 on 2026-02-26 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_pendingtask_action'),
        ('sitevisit', '0002_sitevisitreport_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisitreport',
            name='action',
            field=models.OneToOneField(blank=True, limit_choices_to={'action': 'COMPLETE'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.pendingtask'),
        ),
    ]
