# Generated by Django 6.0.2 on 2026-02-27 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_pendingtask_action'),
        ('sitevisit', '0003_alter_sitevisitreport_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('action', models.OneToOneField(blank=True, limit_choices_to={'action': 'REJECTED'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.pendingtask')),
            ],
        ),
    ]
