# Generated by Django 6.0.2 on 2026-03-06 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisit', '0004_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejected',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rejected',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rejected',
            name='doc_type',
            field=models.CharField(choices=[('ITR', 'ITR Form 16'), ('PAN', 'PAN Card'), ('AADHAAR', 'Aadhaar Card'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='rejected',
            name='frequency',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rejected',
            name='pattern',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rejected',
            name='reason',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
