# Generated by Django 6.0.2 on 2026-03-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisit', '0006_slabreachalert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SLABreachAlert',
        ),
    ]
