# Generated by Django 4.2.7 on 2026-02-18 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('model_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Repossessed', 'Repossessed'), ('In Yard', 'In Yard')], default='Pending', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('High', 'High'), ('Urgent', 'Urgent')], default='Low', max_length=10)),
                ('dpd', models.IntegerField()),
                ('overdue_amount', models.FloatField()),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='vehicle_scans/')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer_reading', models.IntegerField(blank=True, null=True)),
                ('fuel_level', models.CharField(blank=True, choices=[('Empty', 'Empty'), ('Quarter', 'Quarter'), ('Three Quarter', 'Three Quarter'), ('Full', 'Full')], max_length=20, null=True)),
                ('vehicle_condition', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20, null=True)),
                ('tyres_condition', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20, null=True)),
                ('spare_tyre', models.BooleanField(default=False)),
                ('jack', models.BooleanField(default=False)),
                ('toolkit', models.BooleanField(default=False)),
                ('floor_mats', models.BooleanField(default=False)),
                ('music_system', models.BooleanField(default=False)),
                ('rc_available', models.BooleanField(default=False)),
                ('insurance_available', models.BooleanField(default=False)),
                ('pollution_available', models.BooleanField(default=False)),
                ('servicebook_available', models.BooleanField(default=False)),
                ('damages', models.TextField(blank=True, null=True)),
                ('AdditionalNotes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yard_entry', to='recovery.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='YardPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yard_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('yard_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='recovery.yardentry')),
            ],
        ),
        migrations.CreateModel(
            name='RepossessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('repossession_date', models.DateField()),
                ('repossession_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_account_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('in_yard', 'In Yard'), ('auctioned', 'Auctioned'), ('released', 'Released')], default='in_yard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repossessions', to='accounts.account')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS')], max_length=10)),
                ('collection_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_type', models.CharField(choices=[('Call', 'Phone Call'), ('Visit', 'Field Visit'), ('PTP', 'Promise to Pay')], max_length=10)),
                ('disposition', models.CharField(choices=[('Right', 'Right Party Contact'), ('Wrong', 'Wrong Party Contact'), ('No Contact', 'No Contact'), ('Switched Off', 'Switched Off'), ('Call Back', 'Call Back Later'), ('PTP', 'Promise to Pay')], max_length=20)),
                ('contact_person', models.CharField(choices=[('Self', 'Self'), ('Spouse', 'Spouse'), ('Family', 'Family Member')], max_length=20)),
                ('ptp_date', models.DateField(blank=True, null=True)),
                ('ptp_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('voice_recording', models.FileField(blank=True, null=True, upload_to='recordings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Scan', 'Scan'), ('Repossessed', 'Repossessed'), ('Yard Entry', 'Yard Entry')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recovery.vehicle')),
            ],
        ),
    ]
