# Generated by Django 5.2.11 on 2026-03-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payout_Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_payouts', models.IntegerField(default=0)),
                ('Avg_rate', models.IntegerField(default=0)),
                ('max_pool', models.IntegerField(default=0)),
                ('payout_modes', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
