# Generated by Django 5.2.11 on 2026-03-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_payout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout_Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('all', 'All'), ('dsa', 'DSA'), ('broker', 'Broker'), ('lead_partner', 'Lead Partner')], default='all', max_length=20)),
                ('active_payouts', models.IntegerField(default=0)),
                ('Avg_rate', models.IntegerField(default=0)),
                ('max_pool', models.IntegerField(default=0)),
                ('payout_modes', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
