# Generated by Django 5.2.11 on 2026-03-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_payout', '0002_payout_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout_search',
            name='Avg_rate',
        ),
        migrations.RemoveField(
            model_name='payout_search',
            name='active_payouts',
        ),
        migrations.RemoveField(
            model_name='payout_search',
            name='date',
        ),
        migrations.RemoveField(
            model_name='payout_search',
            name='max_pool',
        ),
        migrations.RemoveField(
            model_name='payout_search',
            name='payout_modes',
        ),
        migrations.AlterField(
            model_name='payout_search',
            name='type',
            field=models.CharField(choices=[('dsa', 'DSA'), ('broker', 'Broker'), ('lead_partner', 'Lead Partner')], max_length=20),
        ),
    ]
