# Generated by Django 5.2.11 on 2026-03-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_payout', '0003_remove_payout_search_avg_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout_Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('dsa', 'DSA'), ('broker', 'Broker'), ('lead_partner', 'Lead Partner')], max_length=20)),
                ('flat_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage_rate', models.DecimalField(decimal_places=2, help_text='Enter percentage value (Example: 2.5)', max_digits=5)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cycle_day', models.IntegerField(help_text='Payout cycle day (Example: 5, 10, 15)')),
                ('mode', models.CharField(max_length=50)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('off', 'Off')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
