# Generated by Django 5.2.11 on 2026-03-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_payout', '0004_payout_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout_agent',
            name='action_edit',
            field=models.BooleanField(default=False),
        ),
    ]
