# Generated by Django 5.2.11 on 2026-03-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_payout', '0005_payout_agent_action_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout_agent',
            name='mode',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('neft/rtgs', 'NEFT/RTGS')], default='bank_transfer', max_length=20),
        ),
    ]
