# Generated by Django 6.0.1 on 2026-01-14 16:05

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_loanmanagement_remove_permission_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loanmanagement',
        ),
        migrations.AddField(
            model_name='role',
            name='analytics_reports',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('VIEW_REPORTS', 'View Reports'), ('EXPORT_DATA', 'Export Data'), ('DASHBOARD', 'Dashboard Analytics'), ('PERFORMANCE', 'Performance Reports'), ('CUSTOMER', 'Customer Analytics'), ('FINANCIAL', 'Financial Reports'), ('OPERATIONAL', 'Operational Reports')], max_length=77),
        ),
        migrations.AddField(
            model_name='role',
            name='branch_control',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('VIEW_ALL', 'View All Branches'), ('EDIT_BRANCH', 'Edit Branch'), ('ASSIGN_USERS', 'Assign Users'), ('BRANCH_MANAGEMENT', 'Branch Management'), ('BRANCH_USER_MAPPING', 'Branch-wise User Mapping'), ('BRANCH_LOAN_ACCESS', 'Branch-wise Loan Access'), ('BRANCH_PERFORMANCE', 'Branch Performance Monitoring'), ('GEO', 'Geo / Area Control'), ('BRANCH_CONFIGURATION', 'Branch Configuration Settings')], max_length=134),
        ),
        migrations.AddField(
            model_name='role',
            name='document_management',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('VIEW_DOCUMENTS', 'View Documents'), ('DOWNLOAD_DOCUMENTS', 'Download Documents'), ('UPLOAD_DOCUMENTS', 'Upload Documents'), ('DELETE_DOCUMENTS', 'Delete Documents'), ('DOCUMENT_COLLECTION', 'Document Collection'), ('DOCUMENT_VERIFICATION', 'Document Verification'), ('KYC_DOCUMENTS', 'KYC Documents'), ('PROPERTY', 'Property / Collateral Documents'), ('INCOME', 'Income & Financial Documents')], max_length=139),
        ),
        migrations.AddField(
            model_name='role',
            name='loan_management',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CREATE_LOANS', 'Create Loans'), ('APPROVE_LOANS', 'Approve Loans'), ('VIEW_LOANS', 'View Loans'), ('EDIT_APPLICATIONS', 'Edit Applications'), ('DELETE_LOANS', 'Delete Loans'), ('LOAN_APPLICATION', 'Loan Application Processing'), ('LOAN_LIFECYCLE', 'Loan Lifecycle'), ('CREDIT_ASSESSMENT', 'Credit Assessment'), ('LOAN_CLOSURE', 'Loan Closure'), ('SANCTION_APPROVAL', 'Sanction Approval')], max_length=149),
        ),
        migrations.AddField(
            model_name='role',
            name='system_administration',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AUDIT_LOGS', 'Audit Logs'), ('EDIT_POLICIES', 'Edit Policies'), ('MANAGE_USERS', 'Manage Users'), ('MANAGE_ROLES', 'Manage Roles'), ('MANAGE_BRANCHES', 'Manage Branches'), ('USER_MANAGEMENT', 'User Management'), ('ROLE_PERMISSION', 'Role & Permission Management'), ('TENANT', 'Tenant & Organization Settings'), ('CONFIGURATION', 'Configuration Masters'), ('WORKFLOW_SETUP', 'Workflow Setup')], max_length=134),
        ),
    ]
