# Generated by Django 4.2.7 on 2026-02-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_delete_loanmanagement_role_analytics_reports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CUSTOM', 'Custom Role'), ('SUPERVISOR', 'Supervisor'), ('EXECUTIVE', 'Executive'), ('STANDARD', 'Standard User')], max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10),
        ),
    ]
