# Generated by Django 4.2.7 on 2026-02-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_alter_role_role_type_alter_role_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='status',
            new_name='role_status',
        ),
    ]
