# Generated by Django 4.2.7 on 2026-03-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_reminder_created_by_alter_reminder_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('target', models.CharField(blank=True, max_length=100)),
                ('trend', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(default='overview', max_length=50)),
                ('chart_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video Tutorial'), ('docx', 'Word Document'), ('link', 'External Link')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('summary', models.TextField(blank=True)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('downloads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
