# Generated by Django 4.2.7 on 2026-03-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_report_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('Product Guides', 'Product Guides'), ('Training Materials', 'Training Materials'), ('Forms & Templates', 'Forms & Templates'), ('Support & Help', 'Support & Help'), ('Quick Links', 'Quick Links')], default='Product Guides', max_length=100),
        ),
    ]
