# Generated by Django 4.2.7 on 2026-03-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_resource_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incentive',
        ),
    ]
