# Generated by Django 4.2.7 on 2026-03-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_incentive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
