# Generated by Django 5.2.11 on 2026-03-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_agents', models.IntegerField(default=0)),
                ('active_agents', models.IntegerField(default=0)),
                ('total_payouts', models.IntegerField(default=0)),
                ('lead_generated', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
