# Generated by Django 5.2.11 on 2026-03-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_performance', '0002_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('Lead Partner', 'Lead Partner'), ('Broker', 'Broker'), ('DSA', 'DSA')], max_length=20)),
                ('leads', models.PositiveIntegerField(default=0)),
                ('converted', models.PositiveIntegerField(default=0)),
                ('payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('all_agent_status', models.CharField(choices=[('All', 'All'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('DSA', 'DSA'), ('Broker', 'Broker'), ('Lead Partner', 'Lead Partner')], default='All', max_length=20)),
                ('action_edit', models.BooleanField(default=False)),
                ('action_view', models.BooleanField(default=False)),
                ('action_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
