# Generated by Django 5.2.11 on 2026-03-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_performance', '0003_all_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_agent',
            name='search',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
