# Generated by Django 5.2.11 on 2026-03-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_performance', '0004_all_agent_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('agent_type', models.CharField(choices=[('DSA', 'DSA'), ('Broker', 'Broker'), ('Lead Partner', 'Lead Partner')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('total_leads', models.PositiveIntegerField(default=0)),
                ('converted', models.PositiveIntegerField(default=0)),
                ('payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('score', models.PositiveIntegerField(default=0)),
                ('cancel', models.BooleanField(default=False)),
                ('save_changes', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
