# Generated by Django 5.2.11 on 2026-03-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_performance', '0005_edit_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='View_Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('DSA', 'DSA'), ('Broker', 'Broker'), ('Lead Partner', 'Lead Partner')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('total_leads', models.PositiveIntegerField(default=0)),
                ('converted', models.PositiveIntegerField(default=0)),
                ('payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('performance_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
