# Generated by Django 5.2.11 on 2026-03-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_performance', '0006_view_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='view_agent',
            name='close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='view_agent',
            name='edit_agent',
            field=models.BooleanField(default=False),
        ),
    ]
