# Generated by Django 5.2.11 on 2026-03-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_performance', '0007_view_agent_close_view_agent_edit_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remove_Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=150)),
                ('agent_id', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
    ]
