# Generated by Django 5.2.11 on 2026-03-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_performance', '0008_remove_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remove_agent',
            old_name='is_removed',
            new_name='cancel',
        ),
        migrations.AddField(
            model_name='remove_agent',
            name='yes_remove_agent',
            field=models.BooleanField(default=False),
        ),
    ]
