# Generated by Django 4.2.7 on 2025-12-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_fa_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
