# Generated by Django 4.2.10 on 2026-03-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        ('los', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='loan_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate', to='los.loanapplication'),
        ),
    ]
