# Generated by Django 4.2.7 on 2026-02-27 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commit_Date', models.DateTimeField(auto_now_add=True)),
                ('auto_late_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_overdue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('forecast_type', models.CharField(choices=[('SALES', 'Sales Forecast'), ('REVENUE', 'Revenue Forecast')], max_length=20)),
                ('period', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('quarterly', 'Quaterly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=255)),
                ('loan_number', models.CharField(max_length=50, unique=True)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('SOFT', 'Soft Notice'), ('FIELD', 'Field Visit'), ('court', 'Court Case'), ('LEGAL', 'Legal'), ('SETTLED', 'Settled')], max_length=20)),
                ('Recovery_mode', models.CharField(choices=[('legal', 'Legal'), ('field visit', 'Field Visit'), ('telephonic', 'Telephonic')], max_length=20)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('settlement_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance_And_Analytics.loanaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_type', models.CharField(choices=[('activity', 'Activity'), ('conversion', 'Conversion'), ('financial', 'Financial')], max_length=20)),
                ('target_value', models.FloatField(default=0)),
                ('achieved_value', models.FloatField(default=0)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('assign_to', models.CharField(choices=[('user', 'User'), ('team', 'Team')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=50)),
                ('trend_value', models.FloatField()),
                ('trend_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance_And_Analytics.target')),
            ],
        ),
        migrations.CreateModel(
            name='TargetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=50)),
                ('target_value', models.FloatField()),
                ('achieved_value', models.FloatField()),
                ('achievement', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance_And_Analytics.target')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='settlements/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('recovery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Finance_And_Analytics.recoverycase')),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_mode', models.CharField(blank=True, choices=[('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash')], max_length=20)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partially Paid'), ('UNPAID', 'Unpaid')], max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='repayment_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='Finance_And_Analytics.loanaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PromiseToPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_date', models.DateField()),
                ('commit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection_bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptps', to='Finance_And_Analytics.collectionbucket')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptps', to='Finance_And_Analytics.loanaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('RAW', 'Raw'), ('HOT', 'Hot'), ('FOLLOW_UP', 'Follow Up'), ('CONVERTED', 'Converted')], max_length=20)),
                ('expected_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finance_And_Analytics.campaign')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='Finance_And_Analytics.forecast')),
            ],
        ),
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('CALL', 'Call'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('outcome', models.CharField(choices=[('select outcome', 'Select Outcome'), ('switched off', 'Switched Off'), ('not reachable', 'Not Reachable'), ('ptp captured', 'Ptp Captured'), ('wrong nummber', 'Wrong Number')], default='select outcome', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection_bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='Finance_And_Analytics.collectionbucket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='Finance_And_Analytics.loanaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ConversionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_type', models.CharField(max_length=50)),
                ('stage_from', models.CharField(max_length=50)),
                ('stage_to', models.CharField(max_length=50)),
                ('target_rate', models.FloatField(default=0)),
                ('actual_rate', models.FloatField(default=0)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance_And_Analytics.target')),
            ],
        ),
        migrations.AddField(
            model_name='collectionbucket',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_bucket', to='Finance_And_Analytics.loanaccount'),
        ),
        migrations.CreateModel(
            name='CampaignROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=100)),
                ('spend', models.FloatField(default=0)),
                ('leads', models.IntegerField()),
                ('conversions', models.IntegerField()),
                ('revenue', models.FloatField(default=0)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_rois', to='Finance_And_Analytics.target')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='forecast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='Finance_And_Analytics.forecast'),
        ),
        migrations.CreateModel(
            name='AgentTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.FloatField(default=0)),
                ('achieved_value', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance_And_Analytics.forecast')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('target_count', models.IntegerField(default=0)),
                ('achieved_count', models.IntegerField(default=0)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance_And_Analytics.target')),
            ],
        ),
    ]
