# Generated by Django 5.2.11 on 2026-03-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_Offer_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(max_length=200)),
                ('offer_type', models.CharField(choices=[('BONUS', 'Bonus'), ('FLAT_BONUS', 'Flat Bonus'), ('RATE_HIKE', 'Rate Hike'), ('CASHBACK', 'Cashback'), ('FREE_MONTH', 'Free Month')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SCHEDULED', 'Scheduled'), ('PAUSED', 'Paused')], default='ACTIVE', max_length=20)),
                ('max_usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('bonus_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trigger_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cancel', models.BooleanField(default=False)),
                ('next_step', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
