# Generated by Django 5.2.11 on 2026-03-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promotional_Offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Targetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_agent_type', models.CharField(choices=[('DSA', 'DSA'), ('BROKER', 'Broker'), ('LEAD_PARTNER', 'Lead Partner')], max_length=20)),
                ('target_tenants', models.CharField(choices=[('ALL', 'All'), ('MUMBAI', 'Mumbai'), ('DELHI', 'Delhi'), ('BANGALORE', 'Bangalore'), ('HYDERABAD', 'Hyderabad'), ('CHENNAI', 'Chennai'), ('PUNE', 'Pune')], default='ALL', max_length=20)),
                ('accent_color', models.CharField(choices=[('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('PINK', 'Pink'), ('BLUE', 'Blue'), ('PURPLE', 'Purple'), ('RED', 'Red'), ('NAVY_BLUE', 'Navy Blue'), ('AQUA', 'Aqua')], max_length=20)),
                ('cancel', models.BooleanField(default=False)),
                ('next_step', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
