# Generated by Django 5.2.11 on 2026-03-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promotional_Offers', '0002_new_targetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_offers', models.IntegerField(default=0)),
                ('scheduled', models.IntegerField(default=0)),
                ('active_now', models.IntegerField(default=0)),
                ('total_redemptions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
