# Generated by Django 5.2.11 on 2026-02-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recent_valuation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('assessed_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('assigned_to', models.CharField(choices=[('ravi', 'Ravi Sharma'), ('priya', 'Priya Singh'), ('amit', 'Amit Patel'), ('sunita', 'Sunita Williams')], max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('in_progress', 'In Progress')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
