# Generated by Django 5.2.11 on 2026-02-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recent_valuation', '0004_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='valuation_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
