# Generated by Django 5.2.11 on 2026-02-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recent_valuation', '0005_details_valuation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_id', models.CharField(max_length=50)),
                ('property_deed', models.FileField(blank=True, null=True, upload_to='documents/property_deeds/')),
                ('floor_plan', models.FileField(blank=True, null=True, upload_to='documents/floor_plans/')),
                ('owner_id', models.FileField(blank=True, null=True, upload_to='documents/owner_ids/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
