# Generated by Django 5.2.11 on 2026-02-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recent_valuation', '0006_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='valuation_id',
        ),
    ]
