# Generated by Django 5.2.11 on 2026-02-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recent_valuation', '0007_remove_documents_valuation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_id', models.CharField(max_length=50, unique=True)),
                ('property', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
