# Generated by Django 5.2.11 on 2026-02-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recent_valuation', '0008_recentvaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentvaluation',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('update', 'Update')], default='view', max_length=20),
        ),
    ]
