# Generated by Django 5.2.11 on 2026-02-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('transaction_amount', models.FloatField()),
                ('transaction_count', models.IntegerField()),
                ('device_risk_score', models.FloatField()),
                ('location_risk_score', models.FloatField()),
                ('fraud_probability', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=10)),
                ('is_synthetic_id', models.BooleanField(default=False)),
                ('is_aml_hit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
