# Generated by Django 4.2.7 on 2026-03-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_upload', '0001_initial'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetinglog',
            name='meeting_id',
        ),
        migrations.AddField(
            model_name='meetinglog',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pipeline.meeting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetinglog',
            name='status',
            field=models.CharField(blank=True, choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('No-show', 'No-show'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='meetinglog',
            name='meeting_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('No-show', 'No-show'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meetinglog',
            name='next_action',
            field=models.CharField(blank=True, choices=[('Schedule Follow-up', 'Schedule Follow-up'), ('Move to Deals Stage', 'Move to Deals Stage'), ('Collect Documentations', 'Collect Documentations'), ('Reschedule Meeting', 'Reschedule Meeting'), ('No action Required', 'No action Required')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rawlead',
            name='lead',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_leads', to='bulk_upload.manualentry'),
        ),
    ]
