# Generated by Django 4.2.10 on 2026-03-24 18:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CUSTOM', 'Custom Role'), ('SUPERVISOR', 'Supervisor'), ('EXECUTIVE', 'Executive'), ('STANDARD', 'Standard User')], max_length=20)),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('role_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_management', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CREATE_LOANS', 'Create Loans'), ('APPROVE_LOANS', 'Approve Loans'), ('VIEW_LOANS', 'View Loans'), ('EDIT_APPLICATIONS', 'Edit Applications'), ('DELETE_LOANS', 'Delete Loans'), ('LOAN_APPLICATION', 'Loan Application Processing'), ('LOAN_LIFECYCLE', 'Loan Lifecycle'), ('CREDIT_ASSESSMENT', 'Credit Assessment'), ('LOAN_CLOSURE', 'Loan Closure'), ('SANCTION_APPROVAL', 'Sanction Approval')], max_length=149)),
                ('document_management', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('VIEW_DOCUMENTS', 'View Documents'), ('DOWNLOAD_DOCUMENTS', 'Download Documents'), ('UPLOAD_DOCUMENTS', 'Upload Documents'), ('DELETE_DOCUMENTS', 'Delete Documents'), ('DOCUMENT_COLLECTION', 'Document Collection'), ('DOCUMENT_VERIFICATION', 'Document Verification'), ('KYC_DOCUMENTS', 'KYC Documents'), ('PROPERTY', 'Property / Collateral Documents'), ('INCOME', 'Income & Financial Documents')], max_length=139)),
                ('system_administration', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AUDIT_LOGS', 'Audit Logs'), ('EDIT_POLICIES', 'Edit Policies'), ('MANAGE_USERS', 'Manage Users'), ('MANAGE_ROLES', 'Manage Roles'), ('MANAGE_BRANCHES', 'Manage Branches'), ('USER_MANAGEMENT', 'User Management'), ('ROLE_PERMISSION', 'Role & Permission Management'), ('TENANT', 'Tenant & Organization Settings'), ('CONFIGURATION', 'Configuration Masters'), ('WORKFLOW_SETUP', 'Workflow Setup')], max_length=134)),
                ('analytics_reports', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('VIEW_REPORTS', 'View Reports'), ('EXPORT_DATA', 'Export Data'), ('DASHBOARD', 'Dashboard Analytics'), ('PERFORMANCE', 'Performance Reports'), ('CUSTOMER', 'Customer Analytics'), ('FINANCIAL', 'Financial Reports'), ('OPERATIONAL', 'Operational Reports')], max_length=77)),
                ('branch_control', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('VIEW_ALL', 'View All Branches'), ('EDIT_BRANCH', 'Edit Branch'), ('ASSIGN_USERS', 'Assign Users'), ('BRANCH_MANAGEMENT', 'Branch Management'), ('BRANCH_USER_MAPPING', 'Branch-wise User Mapping'), ('BRANCH_LOAN_ACCESS', 'Branch-wise Loan Access'), ('BRANCH_PERFORMANCE', 'Branch Performance Monitoring'), ('GEO', 'Geo / Area Control'), ('BRANCH_CONFIGURATION', 'Branch Configuration Settings')], max_length=134)),
            ],
        ),
    ]
