# Generated by Django 4.2.7 on 2026-03-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalApiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name or CSS class', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Global API Category',
                'verbose_name_plural': 'Global API Categories',
                'db_table': 'global_api_categories',
            },
        ),
        migrations.CreateModel(
            name='GlobalApiProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(default='inactive', max_length=50)),
                ('base_url', models.URLField(blank=True, max_length=500)),
                ('auth_type', models.CharField(blank=True, max_length=100)),
                ('test_key', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='integrations.globalapicategory')),
            ],
            options={
                'verbose_name': 'Global API Provider',
                'verbose_name_plural': 'Global API Providers',
                'db_table': 'global_api_providers',
            },
        ),
    ]
