# Generated by Django 4.2.7 on 2026-03-11 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_globalapicategory_globalapiprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiintegration',
            name='global_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_integrations', to='integrations.globalapiprovider'),
        ),
    ]
