# Generated by Django 4.2.10 on 2026-03-24 18:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'collections',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('outstanding_principal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tenor_months', models.IntegerField(blank=True, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'loan_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='lms.loanaccount')),
            ],
            options={
                'db_table': 'repayments',
                'ordering': ['-paid_at'],
            },
        ),
    ]
