# Generated by Django 6.0.2 on 2026-02-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('Property Document', 'Property Document'), ('Legal Document', 'Legal Document'), ('Loan Agreement', 'Loan Agreement'), ('Other', 'Other')], max_length=100)),
                ('client_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Validated', 'Validated'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('issues_found', models.BooleanField(default=False)),
            ],
        ),
    ]
