# Generated by Django 6.0.2 on 2026-02-27 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Validation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='client_name',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='issues_found',
        ),
        migrations.AddField(
            model_name='document',
            name='issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Valid', 'Valid'), ('Invalid', 'Invalid')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='UploadDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to='uploaded_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='Document_Validation.document')),
            ],
        ),
    ]
