# Generated by Django 6.0.2 on 2026-02-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Validation', '0002_rename_client_name_document_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='client',
            new_name='client_name',
        ),
        # migrations.RemoveField(
        #     model_name='document',
        #     name='id',
        # ),
        # migrations.RemoveField(
        #     model_name='uploaddocuments',
        #     name='document',
        # ),
        # migrations.AddField(
        #     model_name='document',
        #     name='document_id',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
    ]
