# Generated by Django 6.0.2 on 2026-03-17 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Validation', '0003_rename_client_document_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocuments',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Document_Validation.document'),
        ),
    ]
