# Generated by Django 4.2.10 on 2026-03-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('VIDEO', 'Video'), ('PDF', 'PDF'), ('LINK', 'Link'), ('OTHER', 'Other')], default='PDF', max_length=10)),
                ('file_url', models.URLField(blank=True, help_text='External link if not uploaded', null=True)),
                ('file', models.FileField(blank=True, help_text='Actual document/video file', null=True, upload_to='knowledge_base/')),
                ('size', models.CharField(blank=True, default='2 MB', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'knowledge_resources',
                'ordering': ['-created_at'],
            },
        ),
    ]
