# Generated by Django 4.2.7 on 2025-11-20 16:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('KYC', 'KYC Verification'), ('AML', 'Anti Money Laundering'), ('CREDIT', 'Credit Bureau Check'), ('RISK', 'Risk Assessment')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='tenants.tenant')),
            ],
            options={
                'db_table': 'compliance_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_flags', to='compliance.compliancecheck')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='tenants.tenant')),
            ],
            options={
                'db_table': 'risk_flags',
                'ordering': ['-created_at'],
            },
        ),
    ]
