# Generated by Django 6.0.1 on 2026-02-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='no_of_borrowers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='no_of_users',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
