# Generated by Django 4.2.7 on 2026-02-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_mandate_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='action',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='enach_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=100),
        ),
    ]
