# Generated by Django 5.2.11 on 2026-02-13 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPayMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('sbi', 'State Bank of India'), ('hdfc', 'HDFC Bank'), ('icici', 'ICICI Bank'), ('axis', 'Axis Bank'), ('kotak', 'Kotak Mahindra Bank'), ('pnb', 'Punjab National Bank'), ('other', 'Other Bank')], max_length=50)),
                ('account_holder_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], max_length=20)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('max_debit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debit_day', models.IntegerField()),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('mandate_start_date', models.DateField()),
                ('mandate_end_date', models.DateField()),
                ('authentication_method', models.CharField(choices=[('net_banking', 'Net Banking'), ('debit_card', 'Debit Card')], max_length=20)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('agree_terms', models.BooleanField(default=False)),
                ('authorize_debit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
