# Generated by Django 5.2.11 on 2026-02-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopaymandate',
            name='bank_name',
            field=models.CharField(max_length=50),
        ),
    ]
