# Generated by Django 5.2.11 on 2026-02-14 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_autopaymandate_bank_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupAutoPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_bank', models.CharField(blank=True, choices=[('SBI', 'State Bank of India'), ('HDFC', 'HDFC Bank'), ('ICICI', 'ICICI Bank'), ('AXIS', 'Axis Bank'), ('KOTAK', 'Kotak Mahindra Bank'), ('PNB', 'Punjab National Bank'), ('OTHER', 'Other Bank')], max_length=20, null=True)),
                ('bank_name', models.CharField(max_length=150)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=25)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current')], max_length=20)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AutoPayMandate',
        ),
    ]
