# Generated by Django 5.2.11 on 2026-02-14 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_setupautopay_delete_autopaymandate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='setupautopay',
            name='authentication_method',
            field=models.CharField(blank=True, choices=[('NET_BANKING', 'Net Banking'), ('DEBIT_CARD', 'Debit Card')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='setupautopay',
            name='debit_day_of_month',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='setupautopay',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setupautopay',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupautopay',
            name='emi_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setupautopay',
            name='frequency',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='setupautopay',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='setupautopay',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='setupautopay',
            name='loan_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='setupautopay',
            name='mandate_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setupautopay',
            name='mandate_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setupautopay',
            name='maximum_debit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='setupautopay',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='setupautopay',
            name='principal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='setupautopay',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='setupautopay',
            name='account_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='setupautopay',
            name='account_type',
            field=models.CharField(blank=True, choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='setupautopay',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='setupautopay',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='ManageEMIPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=50)),
                ('emi_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('UPI', 'UPI'), ('NET_BANKING', 'Net Banking'), ('DEBIT_CARD', 'Debit Card'), ('CREDIT_CARD', 'Credit Card')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OVERDUE', 'Overdue'), ('PAID', 'Paid'), ('UPCOMING', 'Upcoming')], default='PENDING', max_length=20)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
