# Generated by Django 5.2.11 on 2026-02-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_setupautopay_authentication_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupautopay',
            name='account_holder_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='setupautopay',
            name='account_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='setupautopay',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current')], max_length=20),
        ),
        migrations.AlterField(
            model_name='setupautopay',
            name='bank_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='setupautopay',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='setupautopay',
            name='ifsc_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='setupautopay',
            name='loan_type',
            field=models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('education', 'Education Loan'), ('consumer_durable', 'Consumer Durable Loan'), ('gold', 'Gold Loan'), ('lap', 'Loan Against Property'), ('vehicle', 'Vehicle Loan'), ('las', 'Loan Against Securities'), ('scf', 'Supply Chain Financing')], max_length=30),
        ),
        migrations.AlterField(
            model_name='setupautopay',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='ManageEMIPayment',
        ),
    ]
