# Generated by Django 5.2.11 on 2026-02-14 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_setupautopay_account_holder_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('education', 'Education Loan'), ('consumer_durable', 'Consumer Durable Loan'), ('gold', 'Gold Loan'), ('lap', 'Loan Against Property'), ('vehicle', 'Vehicle Loan'), ('las', 'Loan Against Securities'), ('scf', 'Supply Chain Financing')], max_length=30)),
                ('emi_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('upi', 'UPI'), ('net_banking', 'Net Banking'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('last_paid_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
