# Generated by Django 5.2.11 on 2026-02-14 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_managepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('education', 'Education Loan'), ('consumer_durable', 'Consumer Durable Loan'), ('gold', 'Gold Loan'), ('lap', 'Loan Against Property'), ('vehicle', 'Vehicle Loan'), ('las', 'Loan Against Securities'), ('scf', 'Supply Chain Financing')], max_length=30)),
                ('transaction_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('net_banking', 'Net Banking'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
