# Generated by Django 5.2.11 on 2026-02-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_recenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='recenttransaction',
            name='emi_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
