# Generated by Django 5.2.11 on 2026-02-16 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_recenttransaction_emi_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('education', 'Education Loan'), ('consumer_durable', 'Consumer Durable Loan'), ('gold', 'Gold Loan'), ('lap', 'Loan Against Property'), ('vehicle', 'Vehicle Loan'), ('las', 'Loan Against Securities'), ('scf', 'Supply Chain Financing')], max_length=30)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('principal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('emi_number', models.PositiveIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('popular_bank', models.CharField(blank=True, choices=[('SBI', 'State Bank of India'), ('HDFC', 'HDFC Bank'), ('ICICI', 'ICICI Bank'), ('AXIS', 'Axis Bank'), ('KOTAK', 'Kotak Mahindra Bank'), ('PNB', 'Punjab National Bank'), ('OTHER', 'Other Bank')], max_length=20, null=True)),
                ('bank_name', models.CharField(max_length=150)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=25)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current')], max_length=20)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('maximum_debit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('debit_day_of_month', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=20, null=True)),
                ('mandate_start_date', models.DateField(blank=True, null=True)),
                ('mandate_end_date', models.DateField(blank=True, null=True)),
                ('authentication_method', models.CharField(blank=True, choices=[('NET_BANKING', 'Net Banking'), ('DEBIT_CARD', 'Debit Card')], max_length=20, null=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
