# Generated by Django 5.2.11 on 2026-03-06 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_emi_remaining_balance_after_emi_and_more'),
        ('payment', '0010_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPayMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=25)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('max_debit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('debit_day', models.IntegerField()),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('auth_method', models.CharField(choices=[('netbanking', 'Net Banking'), ('debitcard', 'Debit Card')], max_length=20)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('mandate_reference', models.CharField(blank=True, help_text='Reference ID returned by bank/NPCI', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autopay', to='loan.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autopay_mandates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=200)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('net_banking', 'Net Banking'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card')], max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('emi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='loan.emi')),
            ],
        ),
    ]
