# Generated by Django 4.2.7 on 2026-01-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_stage', models.CharField(choices=[('DOC_VERIFICATION', 'Document Verification'), ('CREDIT_CHECK', 'Credit Check'), ('DISBURSEMENT', 'Disbursement'), ('MANDATE', 'Mandate')], max_length=50)),
                ('trigger_delay_hours', models.PositiveIntegerField(help_text='Delay in hours before escalation')),
                ('action', models.CharField(choices=[('NOTIFY_SUPERVISOR', 'Notify Supervisor'), ('NOTIFY_MANAGER', 'Notify Manager'), ('AUTO_REJECT', 'Auto Reject')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'escalation_rules',
                'ordering': ['-created_at'],
                'unique_together': {('process_stage', 'action')},
            },
        ),
    ]
