# Generated by Django 4.2.7 on 2026-01-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalationrule',
            name='action',
            field=models.CharField(choices=[('NOTIFY_SUPERVISOR', 'Notify Supervisor'), ('NOTIFY_ADMIN', 'Notify Admin'), ('AUTO_REASSIGN', 'Auto Reassign')], max_length=50),
        ),
        migrations.AlterField(
            model_name='escalationrule',
            name='process_stage',
            field=models.CharField(choices=[('DOC_VERIFICATION', 'Document Verification'), ('DISBURSEMENT', 'Disbursement'), ('UNDERWRITING', 'Underwriting')], max_length=50),
        ),
    ]
