# Generated by Django 6.0.2 on 2026-02-24 16:52

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DialerCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_title', models.CharField(max_length=255)),
                ('product', models.CharField(choices=[('home_loan', 'Home Loan'), ('personal_loan', 'Personal Loan'), ('business_loan', 'Business Loan'), ('car_loan', 'Car Loan'), ('education_loan', 'Education Loan')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('target_audience', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('warm_leads', 'Warm Leads'), ('cold_leads', 'Cold Leads'), ('hot_leads', 'Hot Leads'), ('home_loan', 'Home Loan Prospects'), ('business_owners', 'Business Owners'), ('recent_inquiries', 'Recent Inquiries')], max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('dialer_type', models.CharField(choices=[('preview', 'Preview Dialer'), ('progressive', 'Progressive Dialer'), ('predictive', 'Predictive Dialer')], max_length=50)),
                ('retry_attempts', models.IntegerField(choices=[(1, '1 Attempt'), (2, '2 Attempts'), (3, '3 Attempts'), (4, '4 Attempts'), (5, '5 Attempts')], default=1)),
                ('agent_assignment', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('team_alpha', 'Team Alpha'), ('team_beta', 'Team Beta'), ('external_agency', 'External Agency')], max_length=255)),
                ('call_script', models.FileField(blank=True, null=True, upload_to='call_scripts/')),
                ('timing', models.CharField(choices=[('now', 'Start Now'), ('schedule', 'Schedule for Later')], default='now', max_length=20)),
                ('schedule_datetime', models.DateTimeField(blank=True, null=True)),
                ('auto_schedule_followups', models.BooleanField(default=False)),
                ('followup_retry_hours', models.PositiveIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DialerDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_campaigns', models.IntegerField(default=0)),
                ('total_calls', models.IntegerField(default=0)),
                ('Avg_Connect_Rate', models.IntegerField(default=0)),
                ('engaged_leads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_title', models.CharField(max_length=255)),
                ('product', models.CharField(choices=[('home_loan', 'Home Loan'), ('personal_loan', 'Personal Loan'), ('business_loan', 'Business Loan'), ('car_loan', 'Car Loan'), ('education_loan', 'Education Loan')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('target_audience', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('warm_leads', 'Warm Leads'), ('cold_leads', 'Cold Leads'), ('hot_leads', 'Hot Leads'), ('home_loan', 'Home Loan Prospects'), ('business_owners', 'Business Owners'), ('recent_inquiries', 'Recent Inquiries')], max_length=255)),
                ('email_template', models.CharField(choices=[('professional_blue', 'Professional Blue'), ('modern_gradient', 'Modern Gradient'), ('minimal_white', 'Minimal White')], default='default', max_length=100)),
                ('subject_line', models.CharField(max_length=150)),
                ('preview_text', models.CharField(blank=True, max_length=200, null=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='email_attachments/')),
                ('timing', models.CharField(choices=[('now', 'Start Now'), ('schedule', 'Schedule for Later')], default='now', max_length=20)),
                ('schedule_datetime', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('once', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=20)),
                ('email_open_tracking', models.BooleanField(default=False)),
                ('utm_parameters', models.BooleanField(default=False)),
                ('click_tracking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_campaigns', models.IntegerField(default=0)),
                ('total_sent', models.IntegerField(default=0)),
                ('Avg_open_Rate', models.IntegerField(default=0)),
                ('engaged_leads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmsCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_title', models.CharField(max_length=255)),
                ('product', models.CharField(choices=[('home_loan', 'Home Loan'), ('personal_loan', 'Personal Loan'), ('business_loan', 'Business Loan'), ('car_loan', 'Car Loan'), ('education_loan', 'Education Loan')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('target_audience', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('warm_leads', 'Warm Leads'), ('cold_leads', 'Cold Leads'), ('hot_leads', 'Hot Leads'), ('home_loan', 'Home Loan Prospects'), ('business_owners', 'Business Owners'), ('recent_inquiries', 'Recent Inquiries')], max_length=255)),
                ('sms_template', models.CharField(blank=True, choices=[('promo_1', 'Flash Sale | Flash Sale! Get 20% off all {{product}} loans this week only. Apply here: {{link}}'), ('remind_1', 'Follow-Up | Hi {{firstName}}, following up on your inquiry about {{product}}. Do you have any questions?'), ('alert_1', 'Rate Alert | Good news! Interest rates for {{product}} just dropped to {{rate}}%. Check eligibility: {{link}}')], max_length=50, null=True)),
                ('sender_id', models.CharField(max_length=50)),
                ('message_content', models.TextField()),
                ('timing', models.CharField(choices=[('now', 'Start Now'), ('schedule', 'Schedule for Later')], default='now', max_length=20)),
                ('schedule_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_SMS_campaigns', models.IntegerField(default=0)),
                ('message_sent_today', models.IntegerField(default=0)),
                ('Avg_Click_Rate', models.IntegerField(default=0)),
                ('active_subscribers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_title', models.CharField(max_length=255)),
                ('product', models.CharField(choices=[('home_loan', 'Home Loan'), ('personal_loan', 'Personal Loan'), ('business_loan', 'Business Loan'), ('car_loan', 'Car Loan'), ('education_loan', 'Education Loan')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('post_url', models.URLField(blank=True, null=True)),
                ('hashtags', models.TextField(blank=True)),
                ('timing', models.CharField(choices=[('now', 'Start Now'), ('schedule', 'Schedule for Later')], default='now', max_length=20)),
                ('schedule_datetime', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('once', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=20)),
                ('approver', models.CharField(blank=True, choices=[('manager_a', 'Manager A'), ('manager_b', 'Manager B'), ('marketing_head', 'Marketing Head'), ('ceo', 'CEO')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='socialmediadashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_campaigns', models.IntegerField(default=0)),
                ('total_impressions', models.IntegerField(default=0)),
                ('engagement_Rate', models.IntegerField(default=0)),
                ('click_through_rate', models.IntegerField(default=0)),
                ('leads_generated', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceBroadcastCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_title', models.CharField(max_length=255)),
                ('product', models.CharField(choices=[('home_loan', 'Home Loan'), ('personal_loan', 'Personal Loan'), ('business_loan', 'Business Loan'), ('car_loan', 'Car Loan'), ('education_loan', 'Education Loan')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('target_audience', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('warm_leads', 'Warm Leads'), ('cold_leads', 'Cold Leads'), ('hot_leads', 'Hot Leads'), ('home_loan', 'Home Loan Prospects'), ('business_owners', 'Business Owners'), ('recent_inquiries', 'Recent Inquiries')], max_length=255)),
                ('voice_source', models.CharField(blank=True, choices=[('upload', 'Upload Audio'), ('tts', 'Text To Speech')], max_length=20, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voice_campaigns/')),
                ('retry_attempts', models.IntegerField(choices=[(1, '1 Attempt'), (2, '2 Attempts'), (3, '3 Attempts'), (4, '4 Attempts'), (5, '5 Attempts')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoicebroadcastDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_broadcast', models.IntegerField(default=0)),
                ('total_calls_made', models.IntegerField(default=0)),
                ('Avg_Answer_Rate', models.IntegerField(default=0)),
                ('keypad_reasponses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_title', models.CharField(max_length=255)),
                ('product', models.CharField(choices=[('home_loan', 'Home Loan'), ('personal_loan', 'Personal Loan'), ('business_loan', 'Business Loan'), ('car_loan', 'Car Loan'), ('education_loan', 'Education Loan')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('target_audience', models.CharField(choices=[('warm_leads', 'Warm Leads'), ('cold_leads', 'Cold Leads'), ('hot_leads', 'Hot Leads'), ('home_loan', 'Home Loan Prospects'), ('business_owners', 'Business Owners'), ('recent_inquiries', 'Recent Inquiries')], max_length=50)),
                ('message_body', models.TextField()),
                ('timing', models.CharField(choices=[('now', 'Start Now'), ('schedule', 'Schedule for Later')], max_length=20)),
                ('schedule_datetime', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('once', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=20)),
                ('enable_read_receipts_tracking', models.BooleanField(default=False)),
                ('track_interactive_buttons', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_campaigns', models.IntegerField(default=0)),
                ('total_sent', models.IntegerField(default=0)),
                ('Avg_read_Rate', models.IntegerField(default=0)),
                ('engaged_leads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
