# Generated by Django 4.2.7 on 2026-03-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_key', models.CharField(choices=[('loan', 'Loan Category'), ('product', 'Product Category'), ('document', 'Document Category'), ('lead', 'Lead Category'), ('source', 'Source Category'), ('customer', 'Customer Category'), ('internal_team', 'Internal Team Category'), ('external_team', 'External Team Category'), ('income_type', 'Income Type'), ('employment_type', 'Employment Type'), ('account_type', 'Account Type'), ('gender', 'Gender')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenants.tenant')),
            ],
            options={
                'db_table': 'categories',
                'ordering': ('category_key', 'title'),
            },
        ),
    ]
