# Generated by Django 4.2.7 on 2026-03-20 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_key',
            field=models.CharField(choices=[('loan', 'Loan Category'), ('product', 'Product Category'), ('document', 'Document Category'), ('lead', 'Lead Category'), ('source', 'Source Category'), ('customer', 'Customer Category'), ('internal_team', 'Internal Team Category'), ('external_team', 'External Team Category'), ('income_type', 'Income Type'), ('employment_type', 'Employment Type'), ('account_type', 'Account Type'), ('gender', 'Gender')], max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenants.tenant'),
        ),
    ]
