# Generated by Django 5.2.11 on 2026-02-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypending',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
