# Generated by Django 5.2.11 on 2026-02-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_status', '0002_propertypending_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('property_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('last_check', models.DateField()),
                ('infrastructure_check', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Started', 'Not Started')], default='Completed', max_length=20)),
                ('safety_compliance', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Started', 'Not Started')], default='Pending', max_length=20)),
                ('building_permits', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Started', 'Not Started')], default='Pending', max_length=20)),
                ('environmental_assessment', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Started', 'Not Started')], default='Pending', max_length=20)),
                ('close', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
