# Generated by Django 5.2.11 on 2026-02-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_status', '0003_propertyinprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('property_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(max_length=100)),
                ('status', models.CharField(default='Completed', max_length=20)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=10)),
                ('last_check', models.DateField()),
                ('machinery_inspection', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Started', 'Not Started')], default='Completed', max_length=20)),
                ('storage_facilities', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Started', 'Not Started')], default='Completed', max_length=20)),
                ('waste_management', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Started', 'Not Started')], default='Completed', max_length=20)),
                ('worker_safety_measures', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Started', 'Not Started')], default='Completed', max_length=20)),
                ('close', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='propertyinprogress',
            name='building_permits',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Started', 'Not Started')], default='In progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyinprogress',
            name='environmental_assessment',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Started', 'Not Started')], default='In progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyinprogress',
            name='infrastructure_check',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Started', 'Not Started')], default='In progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyinprogress',
            name='safety_compliance',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Started', 'Not Started')], default='In progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyinprogress',
            name='status',
            field=models.CharField(default='In Progress', max_length=20),
        ),
    ]
