# Generated by Django 5.2.11 on 2026-02-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_status', '0004_propertycompleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('All Properties', 'All Properties')], default='All Properties', max_length=20)),
            ],
        ),
    ]
