# Generated by Django 4.2.7 on 2026-01-02 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('charge_type', models.CharField(choices=[('processing', 'Processing Fee'), ('penalty', 'Penalty'), ('other', 'Other Charges')], max_length=20)),
                ('is_percentage', models.BooleanField(default=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_charge_master',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('coupon_code', models.CharField(max_length=100, unique=True)),
                ('coupon_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('created_user', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_user', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'admin_coupons',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tenants', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_loans', models.IntegerField(default=0)),
                ('monthly_disbursement', models.JSONField(blank=True, default=list)),
                ('loan_status_distribution', models.JSONField(blank=True, default=list)),
                ('recent_activity', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('kyc', 'KYC Document'), ('income', 'Income Document'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_document_types',
            },
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('car', 'Car Loan'), ('mortgage', 'Mortgage Loan (LAP)'), ('home', 'Home Loan'), ('business', 'Business Loan')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_tenure_months', models.IntegerField(default=1)),
                ('max_tenure_months', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_loan_products',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('system', 'System Notification')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=300, null=True)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_notification_templates',
            },
        ),
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_role_master',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subscription_name', models.CharField(max_length=255)),
                ('subscription_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_borrowers', models.IntegerField()),
                ('type_of', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pause', 'Pause'), ('Cancel', 'Cancel')], default='Active', max_length=20)),
                ('created_user', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_user', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'admin_subscriptions',
            },
        ),
    ]
