# Generated by Django 4.2.7 on 2026-01-02 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolemaster',
            name='parent_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_roles', to='adminpanel.rolemaster'),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='charges',
            field=models.ManyToManyField(blank=True, to='adminpanel.chargemaster'),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='required_documents',
            field=models.ManyToManyField(blank=True, to='adminpanel.documenttype'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='adminpanel.subscription'),
        ),
    ]
