# Generated by Django 4.2.7 on 2026-03-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('target', models.CharField(blank=True, max_length=100)),
                ('trend', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(default='overview', max_length=50)),
                ('chart_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='weeklysnapshot',
            options={'ordering': ['-year', '-week_number']},
        ),
        migrations.AlterUniqueTogether(
            name='weeklysnapshot',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='weeklysnapshot',
            name='applications',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklysnapshot',
            name='disbursed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='weeklysnapshot',
            name='total_leads',
            field=models.IntegerField(default=0),
        ),
    ]
