# Generated by Django 4.2.7 on 2026-03-26 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_reportschedule_alter_report_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPerformanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_team_members', models.IntegerField(default=0)),
                ('total_leads_generated', models.IntegerField(default=0)),
                ('total_conversions', models.IntegerField(default=0)),
                ('team_conversion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('average_productivity', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('team_rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_summaries', to=settings.AUTH_USER_MODEL)),
                ('top_performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_performer_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='TeamMemberMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('leads_generated', 'Leads Generated'), ('leads_converted', 'Leads Converted'), ('conversion_rate', 'Conversion Rate'), ('revenue_generated', 'Revenue Generated'), ('applications_processed', 'Applications Processed'), ('calls_made', 'Calls Made'), ('meetings_scheduled', 'Meetings Scheduled'), ('follow_ups_completed', 'Follow-ups Completed'), ('targets_achieved', 'Targets Achieved'), ('customer_satisfaction', 'Customer Satisfaction'), ('response_time', 'Average Response Time'), ('productivity_score', 'Productivity Score')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('target', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('previous_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('achievement_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rank_in_team', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', '-achievement_percentage'],
                'unique_together': {('team_member', 'metric_type', 'period_type', 'period_start')},
            },
        ),
    ]
