# Generated by Django 6.0.1 on 2026-01-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('loan_type', models.CharField(choices=[('PERSONAL', 'Personal Loan'), ('PAYDAY LOAN', 'payday loan'), ('BUSINESS', 'Business Loan'), ('GROUP_LOAN', 'Group loan'), ('VEHICLE', 'Vehicle Loan'), ('UNSECURED_EDUCATION', 'Unsecured education loan'), ('LOAN_AGAINST', 'Loan against property'), ('LOAN_AGAINST', 'Loan against shares'), ('GOLD', 'Gold loan'), ('SECURED_EDUCATION', 'Secured education loan'), ('SUPPLY_CHAIN', 'Supply chain finance'), ('BILL_INVOICE', 'Bill/Invoice Discounting'), ('VIRTUAL_CARD', 'Virtual card'), ('CREDIT_LINE', 'Credit line'), ('AGRICULTURE', 'Agricultureal Loan'), ('MICROFINANCE', 'Microfinance loan'), ('EQUIPMENT', 'Equipement financing'), ('MEDICAL_EMERGENCY', 'Medical emergency loan')], max_length=50)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_tenure', models.PositiveIntegerField(help_text='Months')),
                ('max_tenure', models.PositiveIntegerField(help_text='Months')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
