# Generated by Django 5.2.11 on 2026-02-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_valuation', '0002_assignagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=100)),
                ('property_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('owner_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('pending', 'Pending'), ('completed', 'Completed'), ('schedule', 'Schedule')], default='pending', max_length=20)),
                ('agent', models.CharField(blank=True, choices=[('rajesh_sharma', 'Rajesh Sharma'), ('priya_singh', 'Priya Singh'), ('amit_kumar', 'Amit Kumar')], max_length=50, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('action', models.CharField(blank=True, choices=[('schedule', 'Schedule'), ('reassign', 'Reassign'), ('start_visit', 'Start Visit'), ('view_report', 'View Report')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
