# Generated by Django 5.2.11 on 2026-02-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_valuation', '0003_fieldverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_visit', models.IntegerField(default=0)),
                ('pending_verification', models.IntegerField(default=0)),
                ('active_agents', models.IntegerField(default=0)),
                ('success_rate', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='fieldverification',
            old_name='property_id',
            new_name='field_id',
        ),
        migrations.RenameField(
            model_name='fieldverification',
            old_name='owner_name',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='fieldverification',
            name='status',
            field=models.CharField(choices=[('all_verification', 'All Verification'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('completed', 'Completed'), ('schedule', 'Schedule')], default='all_verification', max_length=20),
        ),
    ]
