# Generated by Django 5.2.11 on 2026-02-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_valuation', '0004_fielddashboard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('visit_notes', models.TextField(blank=True, null=True)),
                ('action_status', models.CharField(choices=[('cancel', 'Cancel'), ('save_visit', 'Save Visit')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
