# Generated by Django 5.2.11 on 2026-02-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_valuation', '0006_statussearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=100)),
                ('verification_date', models.DateField()),
                ('assign_agent', models.CharField(choices=[('priya_singh', 'Priya Singh'), ('amit_kumar', 'Amit Kumar'), ('rajesh_sharma', 'Rajesh Sharma')], max_length=50)),
                ('status', models.CharField(choices=[('schedule', 'Schedule'), ('cancel', 'Cancel')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
