# Generated by Django 5.2.11 on 2026-02-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_valuation', '0007_schedulefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReAssignAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_id', models.CharField(max_length=100)),
                ('select_agent', models.CharField(choices=[('rajesh_sharma', 'Rajesh Sharma'), ('amit_kumar', 'Amit Kumar'), ('priya_singh', 'Priya Singh')], max_length=50)),
                ('status', models.CharField(choices=[('assign', 'Assign'), ('cancel', 'Cancel')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
