# Generated by Django 6.0.2 on 2026-03-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_valuation', '0008_reassignagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleverification',
            name='property_id',
            field=models.CharField(max_length=50),
        ),
    ]
