# Generated by Django 6.0.2 on 2026-03-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_valuation', '0009_alter_scheduleverification_property_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReAssignAgent',
        ),
        migrations.DeleteModel(
            name='ScheduleField',
        ),
        migrations.DeleteModel(
            name='StartVisit',
        ),
        migrations.DeleteModel(
            name='StatusSearch',
        ),
        migrations.RemoveField(
            model_name='assignagent',
            name='status',
        ),
        migrations.RemoveField(
            model_name='scheduleverification',
            name='status',
        ),
    ]
