# Generated by Django 6.0.2 on 2026-03-03 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_valuation', '0010_delete_reassignagent_delete_schedulefield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleverification',
            name='status',
            field=models.CharField(choices=[('all_verification', 'All Verification'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('completed', 'Completed'), ('schedule', 'Schedule')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
