# Generated by Django 6.0.2 on 2026-03-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_valuation', '0011_scheduleverification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleverification',
            name='status',
            field=models.CharField(choices=[('all_verification', 'All Verification'), ('In_Progress', 'In Progress'), ('pending', 'Pending'), ('completed', 'Completed'), ('schedule', 'Schedule')], max_length=50),
        ),
    ]
