# Generated by Django 4.2.7 on 2026-02-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_name', models.CharField(max_length=255)),
                ('api_endpoint_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH')], max_length=20)),
                ('auth_type', models.CharField(choices=[('bearer_token', 'Bearer Token'), ('api_key', 'API Key'), ('basic_auth', 'Basic Auth'), ('oauth_2_0', 'OAuth 2.0')], max_length=20)),
                ('api_key', models.CharField(max_length=128)),
                ('header_key', models.CharField(max_length=255)),
                ('header_value', models.CharField(max_length=255)),
                ('sync_schedule', models.CharField(choices=[('real_time_webhook', 'Real Time Webhook'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('manual_only', 'Manual Only')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_file', models.FileField(blank=True, null=True, upload_to='select_file/')),
                ('product_selection', models.CharField(choices=[('personal_loan', 'Personal Loan'), ('home_loan', 'Home Loan'), ('car_loan', 'Car Loan'), ('business_loan', 'Business Loan'), ('education_loan', 'Education Loan')], max_length=50)),
                ('assign_agent', models.CharField(choices=[('agent_a', 'Agent A'), ('agent_b', 'Agent B'), ('agent_c', 'Agent C'), ('sales_team', 'Sales Team')], max_length=50)),
                ('enable_duplicate_check', models.BooleanField(default=False)),
                ('consent_obtained', models.BooleanField(default=False)),
                ('overwrite_existing_data', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FtpIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_name', models.CharField(max_length=255)),
                ('ftp_host', models.URLField(blank=True, max_length=500, null=True)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('remote_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('frequency', models.CharField(choices=[('once', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('product_selection', models.CharField(choices=[('personal_loan', 'Personal Loan'), ('home_loan', 'Home Loan'), ('car_loan', 'Car Loan'), ('business_loan', 'Business Loan'), ('education_loan', 'Education Loan')], max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
