# Generated by Django 5.2.11 on 2026-02-16 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_lead_updated_at_remove_lead_user_lead_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilesettings',
            options={'verbose_name': 'Profile Settings', 'verbose_name_plural': 'Profile Settings'},
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='allow_contact_requests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='allow_lead_sharing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='blocked_ips',
            field=models.JSONField(blank=True, default=list, help_text='List of blocked IP addresses'),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='change_password_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='login_alerts',
            field=models.BooleanField(default=True, help_text='Alert on new login'),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='profile_visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('CONTACTS_ONLY', 'Contacts Only')], default='PRIVATE', max_length=20),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='require_ip_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='session_timeout_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='show_email',
            field=models.BooleanField(default=False, help_text='Show email on profile'),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='show_phone',
            field=models.BooleanField(default=False, help_text='Show phone number on profile'),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='sms_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='suspicious_activity_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
