# Generated by Django 5.2.11 on 2026-02-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profilesettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Your Privacy Matters - Important Notice', max_length=200)),
                ('introduction', models.TextField(help_text='Opening statement about privacy importance')),
                ('information_we_collect', models.TextField(help_text='Section 1: Information we collect')),
                ('how_we_use_information', models.TextField(help_text='Section 2: How we use your information')),
                ('information_sharing', models.TextField(help_text='Section 3: Information sharing')),
                ('data_security', models.TextField(help_text='Section 4: Data security')),
                ('your_rights_and_choices', models.TextField(help_text='Section 5: Your rights and choices')),
                ('data_retention', models.TextField(help_text='Section 6: Data retention')),
                ('cookies_and_tracking', models.TextField(help_text='Section 7: Cookies and tracking')),
                ('third_party_services', models.TextField(help_text='Section 8: Third party services')),
                ('childrens_privacy', models.TextField(help_text="Section 9: Children's privacy")),
                ('changes_to_policy', models.TextField(help_text='Section 10: Changes to privacy policy')),
                ('contact_us', models.TextField(help_text='Contact information for privacy inquiries')),
                ('quick_summary', models.TextField(help_text='Brief summary of the privacy policy')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policies',
                'ordering': ['-created_at'],
            },
        ),
    ]
