# Generated by Django 4.2.7 on 2026-02-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageOvertime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('rate_multiplier', models.DecimalField(decimal_places=2, help_text='Example: 1.5 = 150%', max_digits=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='AssessmentYear',
            new_name='ManageAssessmentYear',
        ),
        migrations.RenameModel(
            old_name='FinancialYear',
            new_name='ManageFinancialYear',
        ),
        migrations.RenameModel(
            old_name='Holiday',
            new_name='ManageHoliday',
        ),
        migrations.RenameModel(
            old_name='ReportingPeriod',
            new_name='ManageReportingPeriod',
        ),
        migrations.RenameModel(
            old_name='WorkingDay',
            new_name='ManageWorkingDay',
        ),
        migrations.RenameModel(
            old_name='WorkingHour',
            new_name='ManageWorkingHour',
        ),
        migrations.DeleteModel(
            name='Overtime',
        ),
    ]
