# Generated by Django 4.2.7 on 2026-02-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checked_lead', '0001_initial'),
        ('data_lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkedlead',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checked_lead', to='data_lead.lead'),
        ),
    ]
