# Generated by Django 6.0.1 on 2026-01-16 13:29

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Business_name', models.CharField(max_length=255)),
                ('pan_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid PAN format', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('cin', models.CharField(blank=True, max_length=21, null=True, unique=True)),
                ('gstin', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid GSTIN format', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$')])),
                ('registered_address', models.TextField()),
                ('mapped_loan_products', models.JSONField(blank=True, default=list, help_text='List of loan products this business can offer')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'business_master',
                'ordering': ['-created_at'],
            },
        ),
    ]
