# Generated by Django 4.2.7 on 2026-02-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='Business_name',
            new_name='business_name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='mapped_loan_products',
        ),
        migrations.AddField(
            model_name='business',
            name='mapped_products',
            field=models.ManyToManyField(blank=True, related_name='businesses', to='product.product'),
        ),
    ]
