# Generated by Django 4.2.7 on 2026-02-03 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_rename_business_name_business_business_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='registered_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='pan_number',
            new_name='pan',
        ),
    ]
