# Generated by Django 4.2.7 on 2026-02-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_rename_registered_address_business_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='pan',
            new_name='pan_number',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='address',
            new_name='registered_address',
        ),
    ]
