# Generated by Django 5.2.11 on 2026-03-02 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(max_length=20)),
                ('aadhaar_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to='kyc_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_details', to='update_agent.updateagent')),
            ],
        ),
    ]
