# Generated by Django 5.2.11 on 2026-03-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_agent', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(choices=[('mumbai', 'Tenant — Mumbai'), ('delhi', 'Tenant — Delhi'), ('bangalore', 'Tenant — Bangalore'), ('hyderabad', 'Tenant — Hyderabad')], default='mumbai', max_length=20)),
                ('email_notifications', models.BooleanField(default=False, help_text='Receive payout & performance alerts via email')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Receive SMS for lead updates')),
                ('auto_payout', models.BooleanField(default=False, help_text='Automatically process payouts on milestone completion')),
                ('performance_report_access', models.BooleanField(default=False, help_text='Allow agent to view their own performance reports')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
