# Generated by Django 5.2.11 on 2026-03-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_agent', '0004_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='action',
            field=models.CharField(choices=[('previous', 'Previous'), ('save', 'save')], default='save', max_length=20),
        ),
    ]
