# Generated by Django 5.2.11 on 2026-02-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_signin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
                ('sign_up', models.BooleanField(default=False)),
            ],
        ),
    ]
