# Generated by Django 4.2.7 on 2026-02-12 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delinquency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=255)),
                ('dpd', models.PositiveIntegerField()),
                ('overdue_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bucket', models.CharField(choices=[('0-30', '0-30 DPD'), ('31-60', '31-60 DPD'), ('61-90', '61-90 DPD'), ('90+', '90+ DPD (NPA)')], max_length=10)),
                ('action_type', models.CharField(choices=[('CALL', 'Call Borrower'), ('VISIT', 'Field Visit'), ('LEGAL', 'Legal Notice'), ('SETTLED', 'Settled')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lms_account', to='lms.lmsloanaccount')),
            ],
        ),
    ]
