# Generated by Django 5.2.10 on 2026-03-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_agents', models.IntegerField(default=0)),
                ('Active_Agents', models.IntegerField(default=0)),
                ('Total_payouts', models.IntegerField(default=0)),
                ('lead_generated', models.IntegerField(default=0)),
                ('payouts_this_month', models.IntegerField(default=0)),
                ('pending_approvals', models.IntegerField(default=0)),
                ('offers_active', models.IntegerField(default=0)),
                ('Avg_Conversion_Rate', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
