# Generated by Django 5.2.10 on 2026-03-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboard_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('agent_type', models.CharField(max_length=100)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
