# Generated by Django 5.2.11 on 2026-03-03 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_recentagent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(choices=[('DSA_MANAGER', 'DSA Manager'), ('BROKER_ADMIN', 'Broker Admin'), ('LEAD_MANAGER', 'Lead Manager'), ('FINANCE_TEAM', 'Finance Team'), ('OTHER', 'Other')], max_length=20)),
                ('agree_terms', models.BooleanField(default=False)),
                ('create_account', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
