# Generated by Django 5.2.11 on 2026-03-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_create_account_confirm_password_create_account_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('rememeber_me', models.BooleanField(default=False)),
                ('sign_in', models.BooleanField(default=False)),
                ('create_account', models.BooleanField(default=False)),
            ],
        ),
    ]
