# Generated by Django 6.0.2 on 2026-03-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_sign_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_account',
            name='user',
        ),
        migrations.DeleteModel(
            name='Sign_in',
        ),
        migrations.DeleteModel(
            name='Create_Account',
        ),
    ]
