# Generated by Django 5.2.11 on 2026-02-13 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhar_file', models.FileField(blank=True, null=True, upload_to='kyc/aadhar/')),
                ('aadhar_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=10)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('pan_file', models.FileField(blank=True, null=True, upload_to='kyc/pan/')),
                ('pan_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=10)),
                ('digilocker_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('digilocker_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=10)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('credit_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
