# Generated by Django 5.2.11 on 2026-02-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_viewdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='product_type',
            field=models.CharField(choices=[('BUSINESS_LOAN', 'Business Loan'), ('PERSONAL_LOAN', 'Personal Loan'), ('EDUCATIONAL_LOAN', 'Educational Loan'), ('HOME_LOAN', 'Home Loan'), ('CAR_LOAN', 'Car Loan')], max_length=50),
        ),
    ]
