# Generated by Django 4.2.7 on 2026-02-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('WHATSAPP_CLICK', 'WhatsApp Link Clicked'), ('EXPLICIT_REQUEST', 'Explicit Request'), ('VIEWED_DOC', 'Viewed Loan Terms')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DOC_VERIFICATION', 'Doc Verification'), ('FOLLOW_UP', 'Follow Up'), ('READY_FOR_CONSULT', 'Ready for Consult'), ('MEETING_SCHEDULED', 'Meeting Scheduled'), ('SLA_BREACH', 'SLA Breach'), ('CONVERTED', 'Converted to Deal'), ('DORMANT', 'Dormant')], default='DOC_VERIFICATION', max_length=30)),
                ('score', models.PositiveIntegerField(default=0)),
                ('los_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('los_status', models.CharField(default='Pending', max_length=50)),
                ('los_description', models.TextField(blank=True, null=True)),
                ('vendor_source', models.CharField(blank=True, max_length=100, null=True)),
                ('docs_status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
