# Generated by Django 4.2.10 on 2026-03-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('PERSONAL', 'Personal Loan'), ('PAYDAY_LOAN', 'Payday Loan'), ('BUSINESS', 'Business Loan'), ('GROUP_LOAN', 'Group Loan'), ('VEHICLE', 'Vehicle Loan'), ('UNSECURED_EDUCATION', 'Unsecured Education Loan'), ('LOAN_AGAINST_PROPERTY', 'Loan Against Property'), ('LOAN_AGAINST_SHARES', 'Loan Against Shares'), ('GOLD', 'Gold Loan'), ('SECURED_EDUCATION', 'Secured Education Loan'), ('SUPPLY_CHAIN', 'Supply Chain Finance'), ('BILL_INVOICE', 'Bill/Invoice Discounting'), ('VIRTUAL_CARD', 'Virtual Card'), ('CREDIT_LINE', 'Credit Line'), ('AGRICULTURE', 'Agricultural Loan'), ('MICROFINANCE', 'Microfinance Loan'), ('EQUIPMENT', 'Equipment Financing'), ('MEDICAL_EMERGENCY', 'Medical Emergency Loan')], max_length=50)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('next_emi', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20)),
                ('action', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
