# Generated by Django 4.2.10 on 2026-03-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disbursement', '0001_initial'),
        ('activeloans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeloan',
            name='loan_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_loan', to='disbursement.loanaccount'),
        ),
    ]
