# Generated by Django 5.2.11 on 2026-02-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newvaluationrequest',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Cancelled', 'Cancelled')], default='Submitted', max_length=20),
        ),
    ]
