# Generated by Django 5.2.11 on 2026-02-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation_dashboard', '0002_newvaluationrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateNewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Summary', 'Summary'), ('Audit', 'Audit'), ('Data Privacy', 'Data Privacy')], max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.CharField(choices=[('Generated', 'Generated'), ('Cancelled', 'Cancelled')], default='Generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
