# Generated by Django 5.2.11 on 2026-02-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation_dashboard', '0003_generatenewreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_valuations', models.IntegerField(default=0)),
                ('completed_today', models.IntegerField(default=0)),
                ('average_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('success_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
