# Generated by Django 5.2.11 on 2026-02-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation_dashboard', '0004_valuationdashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('All', 'All'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='All', max_length=20)),
                ('property_type', models.CharField(choices=[('All', 'All'), ('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial')], default='All', max_length=50)),
                ('state', models.CharField(choices=[('All', 'All'), ('Mumbai', 'Mumbai'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Bangalore', 'Bangalore'), ('Delhi', 'Delhi')], default='All', max_length=50)),
                ('state_city', models.CharField(max_length=100)),
                ('valuations_count', models.IntegerField(default=0)),
                ('top_property_type', models.CharField(max_length=50)),
                ('avg_loan', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
