# Generated by Django 6.0.2 on 2026-03-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation_dashboard', '0005_locationdistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_id', models.CharField(max_length=20, unique=True)),
                ('property_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('valuation_date', models.DateField()),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('action', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='locationdistribution',
            name='state_city',
        ),
        migrations.AlterField(
            model_name='generatenewreport',
            name='report_type',
            field=models.CharField(choices=[('summary', 'Summary'), ('audit', 'Audit'), ('data_privacy', 'Data Privacy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='generatenewreport',
            name='status',
            field=models.CharField(choices=[('generated', 'Generated'), ('processing', 'Processing')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='locationdistribution',
            name='month',
            field=models.CharField(choices=[('all', 'All'), ('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='locationdistribution',
            name='property_type',
            field=models.CharField(choices=[('all', 'All'), ('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], default='all', max_length=50),
        ),
        migrations.AlterField(
            model_name='locationdistribution',
            name='state',
            field=models.CharField(choices=[('all', 'All'), ('mumbai', 'Mumbai'), ('hyderabad', 'Hyderabad'), ('chennai', 'Chennai'), ('bangalore', 'Bangalore'), ('delhi', 'Delhi')], default='all', max_length=50),
        ),
        migrations.AlterField(
            model_name='locationdistribution',
            name='top_property_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='newvaluationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
