# Generated by Django 4.2.7 on 2025-11-21 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('los', '0003_applicantincome_guarantor_loandocument_loanproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('VOTER_ID', 'Voter ID'), ('PASSPORT', 'Passport')], max_length=20)),
                ('document_number', models.CharField(max_length=200)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='kyc/%Y/%m/%d/')),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kyc_details',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='guarantor',
            name='loan_application',
        ),
        migrations.RemoveField(
            model_name='loandocument',
            name='loan_application',
        ),
        migrations.RemoveField(
            model_name='loandocument',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='statushistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='statushistory',
            name='loan_application',
        ),
        migrations.RemoveField(
            model_name='creditassessment',
            name='recommended_tenure',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='approved_amount',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='approved_tenure',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='product',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='rejected_reason',
        ),
        migrations.AlterField(
            model_name='creditassessment',
            name='approved_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='creditassessment',
            name='status',
            field=models.CharField(default='UNDER_REVIEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterModelTable(
            name='creditassessment',
            table='credit_assessments',
        ),
        migrations.AlterModelTable(
            name='loanapplication',
            table='loan_applications',
        ),
        migrations.DeleteModel(
            name='ApplicantIncome',
        ),
        migrations.DeleteModel(
            name='Guarantor',
        ),
        migrations.DeleteModel(
            name='LoanDocument',
        ),
        migrations.DeleteModel(
            name='LoanProduct',
        ),
        migrations.DeleteModel(
            name='StatusHistory',
        ),
        migrations.AddField(
            model_name='kycdetail',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_details', to='los.loanapplication'),
        ),
    ]
