# Generated by Django 4.2.10 on 2026-03-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('VIDEO', 'Video'), ('PDF', 'PDF')], default='VIDEO', max_length=10)),
                ('duration', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, help_text='Course material (PDF/Video)', null=True, upload_to='training/')),
                ('file_url', models.URLField(blank=True, help_text='Link if not uploaded', null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_modules', to='tenants.tenant')),
            ],
            options={
                'db_table': 'training_modules',
                'ordering': ['-created_at'],
            },
        ),
    ]
