# Generated by Django 6.0.1 on 2026-01-16 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_email', models.EmailField(default='no-reply@platform.com', max_length=254)),
                ('webhook_secret_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSecurityConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_min_length', models.PositiveIntegerField(default=8)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30)),
                ('allow_anonymous_signup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoanConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('min_tenure_months', models.IntegerField()),
                ('currency_symbol', models.CharField(max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
    ]
