# Generated by Django 6.0.1 on 2026-01-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanconfiguration',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='loanconfiguration',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=5),
        ),
        migrations.AlterField(
            model_name='loanconfiguration',
            name='default_interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Default loan interest rate (e.g. 0.12)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanconfiguration',
            name='max_loan_amount',
            field=models.DecimalField(decimal_places=2, help_text='Maximum loan amount', max_digits=14),
        ),
        migrations.AlterField(
            model_name='loanconfiguration',
            name='min_tenure_months',
            field=models.PositiveIntegerField(help_text='Minimum loan tenure in months'),
        ),
    ]
