# Generated by Django 4.2.7 on 2026-02-09 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_delete_user'),
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules_config', to='tenants.tenant')),
            ],
        ),
    ]
