# Generated by Django 4.2.7 on 2026-02-09 19:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_tenantruleconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TenantRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='engine.tenant')),
            ],
            options={
                'db_table': 'tenant_rules',
            },
        ),
        migrations.DeleteModel(
            name='AccessRule',
        ),
        migrations.DeleteModel(
            name='AssignmentRule',
        ),
        migrations.DeleteModel(
            name='SecurityRule',
        ),
        migrations.RemoveField(
            model_name='tenantruleconfig',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='ValidationRule',
        ),
        migrations.DeleteModel(
            name='WorkflowRule',
        ),
        migrations.DeleteModel(
            name='TenantRuleConfig',
        ),
    ]
