# Generated by Django 4.2.7 on 2026-02-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_tenant_tenantrule_delete_accessrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantrule',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='engine.tenant'),
        ),
    ]
