# Generated by Django 5.2.11 on 2026-03-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tenants', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('enterprises', models.IntegerField(default=0)),
                ('total_agents', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
