# Generated by Django 5.2.11 on 2026-03-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(choices=[('WEST', 'West'), ('EAST', 'East'), ('SOUTH', 'South'), ('NORTH', 'North'), ('CENTRAL', 'Central')], max_length=20)),
                ('plan', models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], max_length=20)),
                ('monthly_volume', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('agent_mgmt', models.BooleanField(default=False)),
                ('payout', models.BooleanField(default=False)),
                ('performance', models.BooleanField(default=False)),
                ('offers', models.BooleanField(default=False)),
                ('kyc', models.BooleanField(default=False)),
                ('cancel', models.BooleanField(default=False)),
                ('add_tenant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plan', models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise'), ('ALL', 'All Plans')], max_length=20)),
                ('region', models.CharField(choices=[('EAST', 'East'), ('WEST', 'West'), ('NORTH', 'North'), ('SOUTH', 'South'), ('CENTRAL', 'Central'), ('ALL', 'All Regions')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('agents', models.IntegerField(default=0)),
                ('volume', models.IntegerField(default=0)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=15)),
                ('active_modules', models.TextField(blank=True, null=True)),
                ('edit_tenant', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('deactivate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
