# Generated by Django 5.2.11 on 2026-03-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tenants', '0002_newtenant_showtenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtenant',
            old_name='created_at',
            new_name='joined',
        ),
    ]
