# Generated by Django 5.2.11 on 2026-03-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tenants', '0003_rename_created_at_showtenant_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtenant',
            name='joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
